import type { ZhHansPattern } from './types';

export const advancedPagesZhHansTranslations: Readonly<Record<string, string>> = {
  // Investigator workspace.
  'Where is avoidable token waste concentrated?': '可避免的token浪费主要集中在哪里？',
  'Stored diagnostics ready': '已存储的诊断数据已就绪',
  'Refreshing investigation evidence...': '正在刷新调查证据…',
  'Strict local evidence bundle exported': '已导出严格本地证据包',
  'Refresh evidence': '刷新证据',
  'Refreshing investigation evidence': '正在刷新调查证据',
  'Loading investigation evidence': '正在加载调查证据',
  'Live report services': '实时报告服务',
  'Loaded aggregate fallback': '已加载的聚合回退数据',
  'linked evidence rows': '关联证据记录',
  'Content access enabled': '内容访问已启用',
  'Content access off': '内容访问未启用',
  'Testing': '正在检验',
  'Test hypothesis': '检验假设',
  'Enable in Settings': '在设置中启用',
  'Local pattern': '本地模式',
  'Linked rows': '关联记录',
  'Impact signal': '影响信号',
  'Ranking score': '排序评分',
  'No investigation evidence is available for the loaded scope.': '已加载范围内没有可用的调查证据。',
  'Root-cause workspace': '根因分析工作区',
  'Ranked waste signals, linked evidence, and one explicit verification path.': '对浪费信号排序，关联证据，并提供一条明确的验证路径。',
  'Export evidence': '导出证据',
  'Selected finding': '所选发现',
  'Ranked findings': '已排序发现',
  'Confidence, scope, and evidence stay visible while comparing.': '比较时始终显示置信度、范围和证据。',
  'Recommended change': '建议的改进',
  'Deterministic action from the selected evidence family.': '根据所选证据类别给出的确定性操作。',
  'Verify with': '验证依据',
  'Missing access': '缺少的访问权限',
  'Verify in call': '在调用中验证',
  'Evidence ledger': '证据台账',
  'Each supported row opens the underlying call or thread.': '每条有支撑的记录都可打开对应调用或线程。',
  'Local hypothesis trace': '本地假设追踪',
  'Bounded pattern exploration over the local content/event index.': '在本地内容/事件索引上进行有界模式探索。',
  'Investigation question': '调查问题',
  'Method and caveats': '方法与注意事项',
  'No supported local pattern met the current threshold.': '没有达到当前阈值且有证据支持的本地模式。',
  'Open call': '打开调用',
  'Open thread': '打开线程',
  'No linked record': '没有关联记录',
  'Pattern': '模式',
  'Events': '事件数',
  'Tokens': 'token数',
  'Evidence': '证据',
  'Detail': '详情',
  'Source': '来源',
  'Open': '打开',
  'This finding has no directly linked evidence rows at the current scope.': '当前范围内，此发现没有直接关联的证据记录。',
  'Local Codex logs only; this is not an official OpenAI usage ledger.': '仅使用本地 Codex 日志；这不是 OpenAI 官方用量台账。',
  'Static fallback findings use loaded aggregate rows and cannot identify shell or file rediscovery directly.': '静态回退发现仅使用已加载的聚合记录，无法直接识别 Shell 重复操作或文件重复查找。',
  'Waste fingerprint matrix': '浪费特征矩阵',
  'Recurring diagnostic patterns by thread or aggregate scope; darker cells carry more supporting events.': '按线程或聚合范围展示重复出现的诊断模式；颜色越深，支撑事件越多。',
  'No diagnostic fingerprints are available for the current scope.': '当前范围内没有可用的诊断特征。',
  'Event counts rank evidence volume, not guaranteed token savings.': '事件数只用于衡量证据量，并不保证可以节省相应token。',
  'Use arrow keys to move between cells; use the synchronized table for exact values.': '使用方向键在单元格之间移动；精确数值请查看同步表格。',
  'Waste fingerprints by thread and diagnostic family': '按线程和诊断类别展示浪费特征',
  'Diagnostic family': '诊断类别',
  'Supporting events': '支撑事件数',
  'Finding': '发现',
  'The local report found a repeatable aggregate signal worth reviewing.': '本地报告发现了值得检查的可重复聚合信号。',
  'Inspect the strongest supporting evidence before changing the workflow.': '更改工作流前，请先检查最有力的支撑证据。',
  'No additional access is required for the aggregate evidence.': '查看聚合证据无需额外访问权限。',
  'No raw fragments are included.': '不包含原始片段。',
  'Agentic investigation': '智能体调查',
  'Supporting activity': '支撑活动',
  'Stored diagnostic snapshot': '已存储的诊断快照',
  'Outcome quality remains outside aggregate telemetry.': '聚合遥测无法判断结果质量。',
  'Live diagnostics are unavailable in static mode.': '静态模式下无法使用实时诊断。',
  'This module uses aggregate or stored diagnostic fields and omits raw fragments.': '此模块使用聚合或已存储的诊断字段，并省略原始片段。',
  'Diagnostic snapshot': '诊断快照',
  'Static mode cannot inspect indexed commands or repeated safe file identities.': '静态模式无法检查已索引命令或重复出现的安全文件标识。',
  'Only loaded aggregate call fields are used.': '仅使用已加载的聚合调用字段。',
  'Cache and context pressure': '缓存与上下文压力',
  'Inspect a high-token evidence call, preserve a concise handoff, and start fresh before cold context is resent.': '检查高token证据调用，保留简洁交接信息，并在冷上下文被重新发送前开启新线程。',
  'Aggregate evidence cannot determine whether the large context was necessary for output quality.': '聚合证据无法判断大量上下文是否确实为输出质量所必需。',
  'No prompt or raw tool output is included.': '不包含提示词或原始工具输出。',
  'Loaded call aggregates': '已加载的调用聚合数据',
  'aggregate call': '聚合调用',
  'Open the call and verify whether the context and effort matched the task.': '打开调用，确认上下文和推理强度是否与任务匹配。',
  'Shell churn': 'Shell 重复操作',
  'read pattern': '读取模式',
  'File rediscovery': '文件重复查找',
  'Low output': '低输出',
  'Usage driver': '用量驱动因素',
  'Guided summary': '引导式摘要',
  'File modifications': '文件修改',
  'Read productivity': '读取产出效率',
  'Tool output pressure': '工具输出压力',
  'File read patterns': '文件读取模式',
  'File modification concentration': '文件修改集中度',
  'Read-to-change productivity': '读取到修改的产出效率',
  'Usage concentration': '用量集中度',
  'Guided usage summary': '引导式用量摘要',
  'Diagnostic evidence': '诊断证据',
  'Replace repeated inspection sequences with one scoped script or reusable task.': '将重复检查步骤替换为一个范围明确的脚本或可复用任务。',
  'Keep a short repository orientation note and reuse prior findings before reopening the same files.': '保留简短的仓库导览说明，重新打开相同文件前先复用已有发现。',
  'Bound command output and summarize noisy tool results before the next model turn.': '限制命令输出，并在下一轮模型调用前总结冗长的工具结果。',
  'Use a concise handoff and start a fresh thread before a cold resume resends large context.': '使用简洁交接信息，并在冷恢复重新发送大量上下文前开启新线程。',
  'Inspect the dominant thread before applying a broad workflow change.': '大范围调整工作流前，请先检查占主导地位的线程。',
  'Open the strongest evidence row and verify the suspected waste before changing the workflow.': '更改工作流前，请打开最有力的证据记录并验证疑似浪费。',
  'No diagnostic fingerprints are available.': '没有可用的诊断特征。',
  'Investigation report': '调查报告',
  'high': '高',
  'medium': '中',
  'low': '低',
  'evidence': '有证据',
  'no evidence': '无证据',
  'no_evidence': '无证据',

  // Compression Lab.
  'Context efficiency research': '上下文效率研究',
  'Measure repeated context and tool-output exposure, allocate overlap once, and rank the largest local savings opportunities.': '测量重复上下文和工具输出暴露，统一分配重叠部分，并对最大的本地节省机会排序。',
  'No current profile': '当前没有分析档案',
  'Refresh analysis': '刷新分析',
  'Analyze usage': '分析用量',
  'Analyzing': '正在分析',
  'Compression analysis progress': '上下文压缩分析进度',
  'Waiting for the usage refresh to finish before starting analysis...': '正在等待用量刷新完成，然后开始分析…',
  'Loading the newest exact-scope profile...': '正在加载最新的精确范围分析档案…',
  'Compression Lab jobs run against the local SQLite index and are unavailable in static-file mode.': '上下文压缩实验室任务基于本地 SQLite 索引运行，静态文件模式下不可用。',
  'No analysis for this scope yet': '尚未分析此范围',
  'Start one persistent run. Returning to this scope will reuse the completed profile until its source revision changes.': '启动一次持久化分析。再次进入此范围时，会复用已完成的分析档案，直到源数据修订发生变化。',
  'Overlap-adjusted portfolio': '已扣除重叠的机会组合',
  'Profile complete': '分析档案已完成',
  'Observed exposure': '观测暴露量',
  'Tokens in analyzed components': '已分析组件中的token数',
  'Likely avoidable': '可能可避免',
  'Overlap-adjusted estimate': '已扣除重叠的估算值',
  'Estimate range': '估算范围',
  'Low to high heuristic': '启发式低值至高值',
  'Candidates': '候选项',
  'Opportunity families': '机会类别',
  'Largest overlap-adjusted detector portfolios first.': '优先显示扣除重叠后规模最大的检测器机会组合。',
  'Shared MCP profile': '共享 MCP 分析档案',
  'Compression opportunity families': '上下文压缩机会类别',
  'Family': '类别',
  'Likely savings': '可能节省量',
  'Range': '范围',
  'Profile integrity': '分析档案完整性',
  'Scope, coverage, and disclosure state for this result.': '此结果的范围、覆盖度和披露状态。',
  'Cache': '缓存',
  'Calls covered': '覆盖的调用数',
  'Content mode': '内容模式',
  'Raw fragments': '原始片段',
  'Included': '已包含',
  'Not included': '未包含',
  'Build time': '生成耗时',
  'Coverage warning': '覆盖度警告',
  'Interpretation limits': '解读限制',
  'Exact warm profile': '精确热缓存档案',
  'Incremental profile': '增量分析档案',
  'Reused profile': '复用的分析档案',
  'Fresh profile': '新生成的分析档案',
  'Preparing detector pipeline': '正在准备检测器流水线',
  'detectors': '个检测器',
  'records examined': '条记录已检查',
  'tokens are the current likely savings estimate': '个token是当前可能节省量估算值',
  'ranked candidates. Exposure is measured; avoidability remains an estimate.': '个已排序候选项。暴露量为实测值，可避免程度仍为估算值。',
  'Compression analysis failed': '上下文压缩分析失败',
  'Profile unavailable': '分析档案不可用',
  'aggregate': '聚合数据',
  'unclassified': '未分类',

  // Allowance and limits research.
  'Stored allowance evidence ready': '已存储的限额证据已就绪',
  'Weekly primary signal selected': '已选择每周主要信号',
  '5-hour noisy context selected': '已选择 5 小时噪声上下文',
  'Refreshing allowance evidence...': '正在刷新限额证据…',
  'Allowance refresh failed': '限额证据刷新失败',
  'Allowance evidence refreshed': '限额证据已刷新',
  'Strict allowance evidence exported': '已导出严格限额证据',
  'Weekly hypothesis evaluated against detector output': '已使用检测器输出评估每周假设',
  'Loading allowance history and detector': '正在加载限额历史记录与检测器',
  'Exporting': '正在导出',
  'Live detector payload': '实时检测器数据',
  'Local claim threshold met': '已达到本地结论阈值',
  'Research caution': '研究结论需谨慎',
  'Outside usage possible': '可能存在外部用量',
  'No large outside-usage flag': '未发现明显的外部用量信号',
  'Weekly evidence first, rolling-window context second, and no claim beyond the loaded local data.': '以每周证据为主、滚动窗口上下文为辅，结论不超出已加载的本地数据。',
  'Observed snapshots': '观测快照数',
  'Weekly primary signal': '每周主要信号',
  'Positive spans': '正向区间数',
  'Candidate ratio': '候选比例',
  'Recent vs earlier proxy': '近期与较早期代理值对比',
  'Unexplained movement': '无法解释的变化',
  'Weekly allowance evidence': '每周限额证据',
  '5-hour rolling context': '5 小时滚动窗口上下文',
  'Primary change detector with recent evidence shown first.': '主要变化检测器，优先显示近期证据。',
  'Secondary context only; rolling-window movement is noisy.': '仅作为辅助上下文；滚动窗口变化包含较多噪声。',
  'Allowance window': '限额窗口',
  'Weekly': '每周',
  '5-hour': '5 小时',
  'Hypothesis check': '假设检验',
  'Evaluate a community-style claim using the server detector result.': '使用服务器检测器结果评估社区常见说法。',
  'Allowance hypothesis': '限额假设',
  'Allowance decreased': '限额下降',
  'Behavior stayed stable': '行为保持稳定',
  'Not evaluated': '尚未评估',
  'Choose a claim, then test it against the weekly detector': '选择一种说法，然后使用每周检测器进行检验',
  'The dashboard reports the backend evidence grade; it does not run a separate client-side detector.': '仪表盘展示后端给出的证据等级，不会在客户端另行运行检测器。',
  'More evidence required': '需要更多证据',
  'Test weekly claim': '检验每周限额说法',
  'Evidence grade': '证据等级',
  'What supports or weakens the current result.': '支持或削弱当前结果的因素。',
  'Method': '方法',
  'No candidate split tested': '尚未检验候选分割点',
  'Effect size': '效应量',
  'One-sided p-value': '单侧 p 值',
  '95% median intervals': '95% 中位数区间',
  'Available for both regimes': '两个区间均可用',
  'Available for one regime; the other sample is too small': '一个区间可用；另一个区间样本量过小',
  'Unavailable at the current sample size': '当前样本量下不可用',
  'Method, readiness, and caveats': '方法、就绪度与注意事项',
  'Weekly observations are the primary signal. The 5-hour counter is rolling-window context.': '每周观测是主要信号；5 小时计数器仅作为滚动窗口上下文。',
  'Weekly windows are treated as the primary signal for allowance-change claims.': '涉及限额变化的结论以每周窗口作为主要信号。',
  'Five-hour windows are rolling counters and are downgraded unless supported by weekly evidence.': '5 小时窗口是滚动计数器；没有每周证据支持时，其证据权重会降低。',
  'Unexplained movement can mean allowance behavior changed, but it can also mean usage outside these local Codex logs.': '无法解释的变化可能表示限额行为发生改变，也可能来自本地 Codex 日志之外的用量。',
  'Allowance intelligence uses aggregate token counters and observed usage percentages only.': '限额分析仅使用聚合token计数和观测到的用量百分比。',
  'Strict privacy output omits prompts, assistant text, tool output, file paths, thread names, and record identifiers.': '严格隐私输出会省略提示词、助手文本、工具输出、文件路径、线程名称和记录标识。',
  "This project cannot read OpenAI's internal allowance ledger.": '此项目无法读取 OpenAI 内部限额台账。',
  'Detector summary unavailable.': '检测器摘要不可用。',
  'Insufficient evidence': '证据不足',
  'The loaded weekly history cannot test this claim yet': '已加载的每周历史记录尚不足以检验此说法',
  'More positive weekly spans are required before comparing regimes.': '比较不同区间前，需要更多正向每周区间。',
  'Not supported': '不支持',
  'No weekly regime change was detected': '未检测到每周区间变化',
  'The loaded spans are more consistent with stable local behavior than a lower allowance regime.': '已加载区间更符合本地行为稳定，而不是限额区间下降。',
  'Inconclusive': '无法确定',
  'A local shift is plausible, but attribution is unresolved': '本地变化有一定可能，但归因尚未解决',
  'Usage outside these local Codex logs could explain enough movement that an allowance change is not isolated.': '本地 Codex 日志之外的用量足以解释部分变化，因此无法单独确认限额发生变化。',
  'Supported locally': '本地证据支持',
  'Repeated weekly spans support a lower local capacity regime': '重复出现的每周区间支持本地容量区间下降',
  'The nonparametric detector meets its local sample, effect-size, and p-value thresholds. This remains local evidence, not an internal ledger result.': '非参数检测器已达到本地样本量、效应量和 p 值阈值；这仍是本地证据，并非内部台账结论。',
  'Possible change': '可能发生变化',
  'The direction is consistent, but the sample is not claim-ready': '变化方向一致，但样本尚不足以形成可靠结论',
  'More weekly spans are required on both sides of the candidate split.': '候选分割点两侧都需要更多每周区间。',
  'Static dashboard fallback; local identifiers omitted.': '静态仪表盘回退数据；已省略本地标识。',
  'Live allowance diagnostics are required before testing a change claim.': '检验限额变化说法前，需要实时限额诊断。',
  'Evidence status': '证据状态',
  'Live allowance detector unavailable in this static snapshot': '此静态快照中无法使用实时限额检测器',
  'Projected weekly windows remain visible for orientation, but only the localhost detector can compare normalized positive spans and candidate regimes.': '仍显示预测的每周窗口用于参考，但只有本机检测器能比较标准化正向区间和候选区间。',
  'Descriptive fallback': '描述性回退数据',
  'Loaded aggregate projections are descriptive fallback data, not detector output.': '已加载的聚合预测仅为描述性回退数据，并非检测器输出。',
  'Current result': '当前结果',
  'No weekly regime change detected': '未检测到每周区间变化',
  'The loaded positive spans remain within one local regime.': '已加载的正向区间仍处于同一本地区间。',
  'No change detected': '未检测到变化',
  'The 5-hour counter is behaving like a noisy rolling window': '5 小时计数器表现为噪声较多的滚动窗口',
  'Use weekly spans as the primary signal before drawing a limit conclusion.': '得出限额结论前，请将每周区间作为主要信号。',
  'Counter noise likely': '计数器可能存在噪声',
  'Observed movement is not fully attributable to these local logs': '观测到的变化无法完全归因于这些本地日志',
  'Outside usage remains plausible, so the detector cannot isolate an allowance change.': '仍可能存在外部用量，因此检测器无法单独确认限额变化。',
  'Candidate regime change': '候选区间变化',
  'The direction is consistent, but repeated weekly evidence is still below the public-claim threshold.': '变化方向一致，但重复出现的每周证据仍低于公开结论阈值。',
  'Local sample, effect-size, and p-value thresholds are met. This is still not an OpenAI ledger result.': '本地样本量、效应量和 p 值均已达到阈值；但这仍不是 OpenAI 台账结论。',
  'The local shift is strong, but at least one research-readiness requirement remains unmet.': '本地变化信号较强，但至少一项研究就绪要求尚未满足。',
  'Claim-ready locally': '本地证据已可形成结论',
  'Strong local evidence': '较强本地证据',
  'Not enough weekly evidence to test an allowance change': '每周证据不足，无法检验限额变化',
  'Insufficient data': '数据不足',
  'Consistent': '一致',
  'Stable weekly behavior fits the loaded evidence': '稳定的每周行为符合已加载证据',
  'No candidate split cleared the detector thresholds.': '没有候选分割点达到检测器阈值。',
  'Stable behavior cannot be isolated either': '同样无法单独确认行为稳定',
  'Outside usage and unexplained movement weaken both the stable and decreased hypotheses.': '外部用量和无法解释的变化同时削弱了“稳定”和“下降”两种假设。',
  'A candidate weekly shift conflicts with the stable hypothesis': '候选每周变化与稳定假设冲突',
  'Review the candidate split and readiness criteria before deciding whether the shift is durable.': '判断变化是否持续前，请检查候选分割点和就绪标准。',
  'the candidate split': '候选分割点',
  'Supporting windows': '支撑窗口',
  'Exact local evidence behind the selected chart. Linked rows open the underlying call.': '所选图表背后的精确本地证据；关联记录可打开底层调用。',
  'Scrollable allowance evidence table': '可滚动的限额证据表格',
  'Allowance evidence windows and linked calls': '限额证据窗口与关联调用',
  'Observed': '观测时间',
  'Capacity proxy': '容量代理值',
  'Remaining': '剩余比例',
  'Movement': '变化',
  'Est. credits': '估算点数',
  'Plan': '套餐',
  'Actions': '操作',
  'Aggregate': '聚合数据',
  'No usable evidence rows are available for this window.': '此窗口没有可用的证据记录。',
  'Load more windows': '加载更多窗口',
  'Weekly local capacity evidence': '每周本地容量证据',
  'Observed weekly remaining': '每周剩余比例观测值',
  'Estimated credits per 100 percentage points of observed weekly movement, with exact median intervals when the sample supports them.': '按每周观测变化的每 100 个百分点估算点数；样本充分时显示精确中位数区间。',
  'Loaded aggregate weekly projections for orientation. Exact detector intervals require the localhost allowance endpoints.': '已加载的每周聚合预测仅供参考；精确检测器区间需要本机限额接口。',
  'Observed percentage remaining. The 5-hour view is intentionally secondary because rolling-window movement is noisy.': '观测到的剩余百分比。由于滚动窗口变化噪声较多，5 小时视图仅作为辅助。',
  'weekly spans': '每周区间',
  'weekly primary signal': '每周主要信号',
  'secondary rolling-window context': '辅助滚动窗口上下文',
  'This is a local capacity proxy, not an official OpenAI allowance or billing ledger.': '这是本地容量代理值，并非 OpenAI 官方限额或计费台账。',
  'Rolling-window movement, resets, and sparse observations make the 5-hour counter noisy.': '滚动窗口变化、重置和稀疏观测会使 5 小时计数器包含较多噪声。',
  'Use left and right arrow keys to move through observations. Switch to the table for exact values.': '使用左右方向键浏览观测值；精确数值请切换到表格。',
  '95% low': '95% 下限',
  '95% high': '95% 上限',
  'Observed movement': '观测变化',
  'Weekly evidence span': '每周证据区间',
  'Observed time': '观测时间',
  'Credits per 100% observed movement': '每 100% 观测变化对应点数',
  'Percent remaining': '剩余百分比',
  'Local capacity proxy': '本地容量代理值',
  'Weekly remaining': '每周剩余比例',
  'Noisy 5-hour remaining': '含噪声的 5 小时剩余比例',
  'Candidate shift · outside usage possible': '候选变化 · 可能存在外部用量',
  'Candidate weekly regime shift': '候选每周区间变化',
  'Observed counter reset or rollback': '观测到计数器重置或回退',
  'Observation gap': '观测间隔',
  'weekly span': '每周区间',
  'observation': '观测值',
  'strong local evidence': '较强本地证据',
  'possible regime change': '可能发生区间变化',
  'inconclusive other usage possible': '无法确定，可能存在其他用量',
  'no change detected': '未检测到变化',
  'counter noise likely': '计数器可能存在噪声',
  'insufficient data': '数据不足',

  // Cache and context workspace.
  'Cache And Context Lab': '缓存与上下文实验室',
  'Cache behavior, cold resumes, context pressure, optimization recommendations.': '分析缓存行为、冷恢复、上下文压力和优化建议。',
  'Full-scope endpoints': '完整范围接口',
  'Snapshot fallback': '快照回退数据',
  'Context safe': '上下文安全',
  'Loading cache and context evidence': '正在加载缓存与上下文证据',
  'Cache Hit Rate & Context Window Over Time': '缓存命中率与上下文窗口趋势',
  'Cache reuse and context pressure': '缓存复用与上下文压力',
  'Percent': '百分比',
  'Cache Reuse Heatmap': '缓存复用热力图',
  'No cache heatmap rows': '没有缓存热力图记录',
  'Scrollable cache reuse heatmap': '可滚动的缓存复用热力图',
  'Cache reuse heatmap': '缓存复用热力图',
  'No cache heatmap rows in the current aggregate snapshot.': '当前聚合快照中没有缓存热力图记录。',
  'Threads Overview': '线程概览',
  'Cold resume and cache efficiency signals': '冷恢复与缓存效率信号',
  'Hover previews; rows open latest call': '悬停可预览；单击记录可打开最新调用',
  'Cache context threads overview': '缓存与上下文线程概览',
  'Selected Thread Diagnosis': '所选线程诊断',
  'No grouped thread is available in the current aggregate snapshot.': '当前聚合快照中没有可用的分组线程。',
  'Efficiency Profile': '效率概况',
  'Cache hit': '缓存命中率',
  'Est. cost': '估算成本',
  'Cost/call': '单次调用成本',
  'Cache Windows': '缓存窗口',
  'Weekly reuse': '每周复用',
  'No heatmap row': '没有热力图记录',
  'no heatmap row': '没有热力图记录',
  'No weekly cache heatmap row matches this selected thread.': '没有与所选线程匹配的每周缓存热力图记录。',
  'No loaded aggregate call rows match this selected thread.': '没有与所选线程匹配的已加载聚合调用记录。',
  'Diagnosis Basis': '诊断依据',
  'Suggested Actions': '建议操作',
  'Summarize before the next work session.': '在下次工作会话前先做摘要。',
  'Split completed topics or reduce repeated uncached context.': '拆分已完成的主题，或减少重复的未缓存上下文。',
  'Open a related call and inspect whether model effort was justified.': '打开相关调用，检查模型推理强度是否合理。',
  'Keep the thread warm and continue monitoring cache reuse.': '保持线程热缓存，并继续监控缓存复用。',
  'Thread summaries': '线程摘要',
  'Selected thread calls': '所选线程调用',
  'Focused evidence': '聚焦证据',
  'server-side aggregate': '服务器端聚合数据',
  'review cache reuse': '检查缓存复用',
  'Window': '窗口',
};

export const advancedPagesZhHansPatterns: ReadonlyArray<ZhHansPattern> = [
  // Investigator status, evidence counts, and action labels. Finding titles and patterns are preserved.
  { pattern: /^Live evidence refreshed · ([\d,.]+) diagnostic modules$/u, replace: '实时证据已刷新 · $1 个诊断模块' },
  { pattern: /^Refresh failed: (.+)$/u, replace: '刷新失败：$1' },
  { pattern: /^Live report unavailable: (.+)$/u, replace: '实时报告不可用：$1' },
  { pattern: /^Investigation report unavailable: (.+)$/u, replace: '调查报告不可用：$1' },
  { pattern: /^(.+) unavailable: (.+)$/u, replace: '$1不可用：$2' },
  { pattern: /^Loading diagnostics ([\d,.]+)\/([\d,.]+)$/u, replace: '正在加载诊断模块 $1/$2' },
  { pattern: /^([\d,.]+) diagnostic modules$/u, replace: '$1 个诊断模块' },
  { pattern: /^([\d,.]+) ranked findings$/u, replace: '$1 个已排序发现' },
  { pattern: /^([\d,.]+) signals$/u, replace: '$1 个信号' },
  { pattern: /^([\d,.]+) rows$/u, replace: '$1 条记录' },
  { pattern: /^([\d,.]+) linked$/u, replace: '已关联 $1 条' },
  { pattern: /^([\d,.]+) score$/u, replace: '评分 $1' },
  { pattern: /^Evidence ledger for (.+)$/u, replace: (_match, finding) => `“${advancedUiTermZhHans(finding)}”的证据台账` },
  { pattern: /^(.+) · ([\d,.]+) events · ([\d,.]+(?:[KMBT])?) tokens$/iu, replace: '$1 · $2 个事件 · $3 个token' },
  {
    pattern: /^history (active|all) · no stored snapshot\. Function calls: ([\d,.]+); Function outputs: ([\d,.]+); Original tokens: ([\d,.]+)\.$/u,
    replace: (_match, scope, calls, outputs, tokens) =>
      `历史范围：${scope === 'all' ? '全部历史记录' : '活动会话'} · 没有已存储快照。函数调用：${calls}；函数输出：${outputs}；原始token数：${tokens}。`,
  },
  { pattern: /^(Open call|Open thread|No linked record) for (.+)$/u, replace: (_match, action, patternName) => `${investigationActionZhHans(action)}：${patternName}` },
  { pattern: /^Copy call link for (.+)$/u, replace: '复制以下模式对应的调用链接：$1' },
  { pattern: /^Open call evidence for (.+)$/u, replace: '打开以下模式的调用证据：$1' },
  { pattern: /^Open thread evidence for (.+)$/u, replace: '打开以下模式的线程证据：$1' },
  { pattern: /^([\d,.]+) loaded calls combine weak cache reuse or elevated context pressure\.$/u, replace: '$1 次已加载调用存在缓存复用较弱或上下文压力升高的情况。' },
  { pattern: /^(.+) is the highest-ranked of ([\d,.]+) findings with ([\d,.]+) supporting rows\.$/u, replace: (_match, finding, count, rows) => `“${advancedUiTermZhHans(finding)}”在 ${count} 个发现中排名最高，并有 ${rows} 条支撑记录。` },
  { pattern: /^([\d,.]+(?:\.\d+)?)% cache · ([\d,.]+(?:[KMBT])?) output$/iu, replace: '缓存 $1% · 输出 $2 个token' },

  // Compression progress and estimates.
  { pattern: /^Compression analysis failed: (.+)$/u, replace: '上下文压缩分析失败：$1' },
  { pattern: /^Profile unavailable: (.+)$/u, replace: '分析档案不可用：$1' },
  { pattern: /^([\d,.]+) of ([\d,.]+) detectors \/ ([\d,.]+) records examined$/u, replace: '检测器 $1/$2 · 已检查 $3 条记录' },
  { pattern: /^([\d,.]+(?:[KMBT])?) tokens are the current likely savings estimate$/iu, replace: '当前可能节省量估算为 $1 个token' },
  { pattern: /^([\d,.]+) to ([\d,.]+) across ([\d,.]+) ranked candidates\. Exposure is measured; avoidability remains an estimate\.$/u, replace: '在 $3 个已排序候选项中，估算范围为 $1 至 $2。暴露量为实测值，可避免程度仍为估算值。' },
  { pattern: /^([\d,.]+) coverage warnings$/u, replace: '$1 条覆盖度警告' },
  { pattern: /^([\d,.]+) detector families$/u, replace: '$1 个检测器类别' },
  { pattern: /^(.+) detector$/u, replace: '$1 检测器' },

  // Allowance research. Plans, dates, and detector errors are preserved verbatim.
  { pattern: /^Export failed: (.+)$/u, replace: '导出失败：$1' },
  { pattern: /^Live detector unavailable: (.+)$/u, replace: '实时检测器不可用：$1' },
  { pattern: /^([\d,.]+) weekly spans · (.+)$/u, replace: '$1 个每周区间 · $2' },
  { pattern: /^([\d,.]+) resets \/ rollbacks$/u, replace: '$1 次重置/回退' },
  { pattern: /^([\d,.]+) positive weekly spans are loaded\. More observations are needed before comparing regimes\.$/u, replace: '已加载 $1 个正向每周区间。比较不同区间前还需要更多观测值。' },
  { pattern: /^Weekly behavior shifted around (.+)$/u, replace: '每周行为在 $1 附近发生变化' },
  { pattern: /^The recent local capacity proxy is ([\d,.]+)% of the earlier regime after (.+)$/u, replace: '$2 之后，近期本地容量代理值为较早区间的 $1%' },
  { pattern: /^Span ([\d,.]+)$/u, replace: '区间 $1' },
  { pattern: /^Observation ([\d,.]+)$/u, replace: '观测 $1' },
  { pattern: /^Open allowance evidence call observed (.+)$/u, replace: '打开以下观测对应的限额证据调用：$1' },
  { pattern: /^Copy link to allowance evidence call observed (.+)$/u, replace: '复制以下观测对应的限额证据调用链接：$1' },
  { pattern: /^At least two (weekly spans|observations) are required for a trend\.$/u, replace: (_match, kind) => `至少需要两个${kind === 'weekly spans' ? '每周区间' : '观测值'}才能显示趋势。` },
  { pattern: /^(.+) · weekly primary signal$/u, replace: '$1 · 每周主要信号' },
  { pattern: /^(.+) · secondary rolling-window context$/u, replace: '$1 · 辅助滚动窗口上下文' },
  { pattern: /^(Weekly local capacity evidence|Observed weekly remaining|5-hour rolling context) evidence$/u, replace: (_match, title) => `${allowanceChartTitleZhHans(title)}证据` },
  { pattern: /^Only ([\d,.]+) usable weekly span is available\.$/u, replace: '仅有 $1 个可用的每周区间。' },
  { pattern: /^Only ([\d,.]+) usable observation is available\.$/u, replace: '仅有 $1 个可用的观测值。' },
  { pattern: /^([\d,.]+) 5-hour observations are shown as noisy rolling-window context, not primary allowance evidence\.$/u, replace: '当前显示 $1 个 5 小时观测值，它们仅作为含噪声的滚动窗口上下文，而非主要限额证据。' },

  // Cache/context counts and labels. Thread names and model names remain unchanged.
  { pattern: /^([\d,.]+) cache windows$/u, replace: '$1 个缓存窗口' },
  { pattern: /^Selected (.+): ([\d,.]+(?:\.\d+)?)% cache$/u, replace: '已选择“$1”：缓存 $2%' },
  { pattern: /^Selected (.+)$/u, replace: '已选择：$1' },
  { pattern: /^Showing ([\d,.]+) of ([\d,.]+) full-scope thread summaries\.$/u, replace: '显示 $1 / $2 个完整范围线程摘要。' },
  { pattern: /^([\d,.]+) loaded$/u, replace: '已加载 $1 条' },
  { pattern: /^([\d,.]+) loaded calls$/u, replace: '已加载 $1 次调用' },
  { pattern: /^([\d,.]+(?:[KMBT])?) tokens - ([\d,.]+(?:\.\d+)?)% cache$/iu, replace: '$1 个token - 缓存 $2%' },
  { pattern: /^([\d,.]+(?:[KMBT])?) total tokens$/iu, replace: '共 $1 个token' },
  { pattern: /^Window ([\d,.]+)$/u, replace: '窗口 $1' },
  { pattern: /^Cache windows for (.+)$/u, replace: '“$1”的缓存窗口' },
  { pattern: /^Open investigator for cache thread call (.+)$/u, replace: '在分析器中打开缓存线程调用：$1' },
  { pattern: /^Copy link for cache thread call (.+)$/u, replace: '复制缓存线程调用链接：$1' },
  { pattern: /^Risk: (High|Medium|Low) cold-resume score$/u, replace: (_match, risk) => `风险：冷恢复评分${riskZhHans(risk)}` },
  { pattern: /^(High|Medium|Low) risk$/u, replace: (_match, risk) => `${riskZhHans(risk)}风险` },
  { pattern: /^Cache: ([\d,.]+(?:\.\d+)?)% hit rate; action threshold below 35%$/u, replace: '缓存：命中率 $1%；操作阈值低于 35%' },
  { pattern: /^Cost: (.+) per call; inspect threshold above \$1\.00$/u, replace: '成本：每次调用 $1；检查阈值高于 $1.00' },
  { pattern: /^Evidence: ([\d,.]+) loaded calls, ([\d,.]+) cache windows$/u, replace: '证据：已加载 $1 次调用，包含 $2 个缓存窗口' },
  { pattern: /^Evidence: ([\d,.]+) loaded calls, no heatmap row$/u, replace: '证据：已加载 $1 次调用，没有热力图记录' },
];

function investigationActionZhHans(action: string): string {
  if (action === 'Open call') return '打开调用';
  if (action === 'Open thread') return '打开线程';
  return '没有关联记录';
}

function advancedUiTermZhHans(value: string): string {
  return advancedPagesZhHansTranslations[value] ?? value;
}

function allowanceChartTitleZhHans(title: string): string {
  if (title === 'Weekly local capacity evidence') return '每周本地容量';
  if (title === 'Observed weekly remaining') return '每周剩余比例观测值';
  return '5 小时滚动窗口上下文';
}

function riskZhHans(risk: string): string {
  if (risk === 'High') return '高';
  if (risk === 'Medium') return '中';
  return '低';
}
