import type { ZhHansPattern } from './types';

export const commonZhHansTranslations: Readonly<Record<string, string>> = {
  'Active history': '活动记录',
  'Active sessions': '活动会话',
  'Active sessions only': '仅活动会话',
  'Aggregate fallback': '聚合数据回退',
  'Aggregate only': '仅聚合数据',
  'All calls visible': '显示全部调用',
  'All history selected': '已选择全部历史记录',
  'All time': '全部时间',
  'Analysis scope': '分析范围',
  'Auto refresh': '自动刷新',
  'Auto refresh paused': '自动刷新已暂停',
  'Auto refresh pauses on this evidence-heavy view': '此证据密集页面会暂停自动刷新',
  'Available languages': '可用语言',
  'Back to top': '返回顶部',
  'Browse all calls': '浏览全部调用',
  'Cancel refresh': '取消刷新',
  'Chart view': '图表视图',
  'Chart unavailable. Use the synchronized table view.': '图表不可用，请使用同步表格视图。',
  'Caveats:': '注意事项：',
  'Choose loaded call window': '选择调用加载范围',
  'Clear filters': '清除筛选条件',
  'Clipboard unavailable': '剪贴板不可用',
  'Columns': '列',
  'Commands': '命令',
  'Copy call link': '复制调用链接',
  'Copy investigator link': '复制分析器链接',
  'Copy unavailable in browser': '浏览器中无法复制',
  'Custom': '自定义',
  'Dashboard filters': '仪表盘筛选器',
  'Dashboard route could not load': '仪表盘页面无法加载',
  'Dashboard toolbar': '仪表盘工具栏',
  'Day': '日期',
  'Dense': '紧凑',
  'Daily': '每日',
  'Density': '显示密度',
  'Endpoint fallback': '接口回退数据',
  'Endpoint unavailable.': '接口不可用。',
  'Export': '导出',
  'Export overview': '导出概览',
  'Export SVG': '导出 SVG',
  'Export visualization as SVG': '将可视化导出为 SVG',
  'Files': '文件',
  'FILTERS': '筛选',
  'Filters': '筛选',
  'From': '来源',
  'Global confidence filter': '全局置信度筛选器',
  'Global effort filter': '全局推理强度筛选器',
  'Global end date': '全局结束日期',
  'Global model filter': '全局模型筛选器',
  'Global start date': '全局开始日期',
  'Global time filter': '全局时间筛选器',
  'History scope': '历史记录范围',
  'Incomplete page evidence': '页面证据不完整',
  'Lifecycle': '生命周期',
  'Invalid date range': '日期范围无效',
  'Last 24h': '过去 24 小时',
  'Last 7 days': '过去 7 天',
  'Live API': '实时 API',
  'Loaded snapshot': '已加载快照',
  'Loading dashboard': '正在加载仪表盘',
  'Loading renderer...': '正在加载图表渲染器…',
  'Local API token present for refresh actions.': '已提供本地 API 令牌，可执行刷新操作。',
  'Local data only': '仅使用本地数据',
  'Models': '模型',
  'More columns': '更多列',
  'No data': '暂无数据',
  'No matching evidence': '没有匹配的证据',
  'No rows match current filters.': '没有符合当前筛选条件的记录。',
  'Primary': '主导航',
  'Privacy': '隐私',
  'Quick Links': '快捷入口',
  'Recent': '最近记录',
  'Recent rows': '最近记录',
  'Refresh data': '刷新数据',
  'Restore defaults': '恢复默认设置',
  'Restoring the local usage workspace...': '正在恢复本地用量工作区…',
  'Retry': '重试',
  'Roomy': '宽松',
  'Search': '搜索',
  'Selected': '已选择',
  'Show more columns': '显示更多列',
  'Static embedded snapshot': '静态内嵌快照',
  'Static embedded snapshot; live refresh is unavailable.': '当前为静态内嵌快照，无法实时刷新。',
  'Stored snapshot': '已存储的快照',
  'Stored snapshot loaded just now': '刚刚载入已存储的快照',
  'Table view': '表格视图',
  'Table': '表格',
  'Tokens line chart': 'token折线图',
  'Tokens history. Recent dates are shown first; scroll left for earlier dates.': 'token历史记录。近期日期优先显示；向左滚动可查看更早日期。',
  'Cache % line chart': '缓存比例折线图',
  'Cache % history. Recent dates are shown first; scroll left for earlier dates.': '缓存比例历史记录。近期日期优先显示；向左滚动可查看更早日期。',
  'Text direction': '文字方向',
  'Today': '今天',
  'Unofficial project notice': '非官方项目声明',
  'Unofficial project.': '非官方项目。',
  'Updated': '已更新',
  'Updated unversioned': '更新于未标记版本',
  'Updating evidence': '正在更新证据',
  'Updating page evidence': '正在更新页面证据',
  'Working on full-scope evidence': '正在处理完整范围的证据',
  'Usage summary ready': '用量摘要已就绪',
  'Recommendations loading': '建议正在加载',
  'Recommendations ready': '建议已就绪',
  '24 hours': '24 小时',
  '7 days': '7 天',
  'Aggregate Identity': '聚合记录标识',
  'Aggregate summary': '聚合摘要',
  'Auto': '自动',
  'Cache And Context': '缓存与上下文',
  'Cache Reuse': '缓存复用率',
  'Cached': '缓存输入',
  'Cached %': '缓存比例',
  'Cached Input': '缓存输入',
  'Call filters': '调用筛选器',
  'Compression Lab': '上下文压缩实验室',
  'Context %': '上下文比例',
  'Context window': '上下文窗口',
  'Diagnostics Notebook': '诊断工作台',
  'Duration': '耗时',
  'Effort': '推理强度',
  'Input Tokens': '输入token',
  'Initiated': '发起方',
  'Investigate': '调查分析',
  'Investigation': '调查分析',
  'Limits': '使用限额',
  'Loaded usage metrics': '已加载的用量指标',
  'Loading overview evidence': '正在加载概览证据',
  'Loading overview evidence modules': '正在加载概览证据模块',
  'Loaded token accounting': '已加载的token统计',
  'Local telemetry console': '本地用量分析控制台',
  'No calls are available for token accounting.': '没有可用于token统计的调用。',
  'No daily token movement is available.': '没有可用的每日token变化数据。',
  'No dated aggregate usage is available in this scope.': '当前范围内没有带日期的聚合用量数据。',
  'No loaded calls match the current search.': '已加载的调用中没有符合当前搜索条件的记录。',
  'No token accounting is available in this scope.': '当前范围内没有可用的token统计数据。',
  'Not made by, affiliated with, endorsed by, sponsored by, or supported by OpenAI.': '本项目并非由 OpenAI 制作，也不隶属于 OpenAI，未获其认可、赞助或支持。',
  'Overview': '概览',
  'Prev Gap': '与上次间隔',
  'Pricing configured': '已配置定价',
  'Project metadata is shown normally.': '项目元数据按正常模式显示。',
  'Recent token movement': '近期token变化',
  'Daily input, cached reuse, and output volume in the selected history scope.': '所选历史范围内的每日输入、缓存复用和输出量。',
  'Daily aggregates describe local records; they do not represent OpenAI billing.': '每日聚合仅描述本地记录，不代表 OpenAI 账单。',
  'Categories mirror reported fields and may overlap; flow widths are accounting, not causality or billed cost.': '分类与日志报告字段一致，彼此可能重叠；流量宽度仅表示统计量，不代表因果关系或计费成本。',
  'The four reported token categories across calls currently loaded in the dashboard.': '仪表盘当前已加载调用中的四类token统计。',
  'The important changes first, with direct paths into supporting evidence.': '优先展示重要变化，并可直接查看支撑证据。',
  'reported token accounting': '日志报告的token统计',
  'loaded evidence rows': '已加载的证据记录',
  'loaded calls only': '仅统计已加载调用',
  'calls with mapped cost and credit rates': '已匹配成本与点数费率的调用',
  'Estimated credits': '估算点数',
  'risk: low cache reuse': '风险：缓存复用率低',
  'Reasoning': '推理输出',
  'Reasoning Output': '推理输出',
  'Reports': '报告',
  'Settings': '设置',
  'Signals': '信号',
  'CACHE': '缓存',
  'CTX': '上下文',
  'EST': '估算',
  'LO': '低输出',
  'RSN': '推理',
  'BIG': '长线程',
  'PRICE': '定价',
  'SUB': '子智能体',
  'Sort by Cached %': '按缓存比例排序',
  'Sort by Cached Input': '按缓存输入排序',
  'Sort by Codex Credits': '按 Codex 点数排序',
  'Sort by Context %': '按上下文比例排序',
  'Sort by Duration': '按耗时排序',
  'Sort by Effort': '按推理强度排序',
  'Sort by Est. Cost': '按估算成本排序',
  'Sort by Initiated': '按发起方排序',
  'Sort by Input Tokens': '按输入token排序',
  'Sort by Model': '按模型排序',
  'Sort by Output Tokens': '按输出token排序',
  'Sort by Prev Gap': '按与上次间隔排序',
  'Sort by Reasoning Output': '按推理输出排序',
  'Sort by Signals': '按信号排序',
  'Sort by Thread': '按线程排序',
  'Sort by Time': '按时间排序',
  'Sort by Total Tokens': '按token总数排序',
  'Sort by Uncached Input': '按未缓存输入排序',
  'Total Calls': '调用总数',
  'Total Tokens': 'token总数',
  'Total Tokens breakdown': 'token总数明细',
  'Estimated Cost breakdown': '估算成本明细',
  'Uncached': '未缓存输入',
  'Uncached Input': '未缓存输入',
  'Usage pulse': '用量脉搏',
  'Visualization contract error': '可视化定义错误',
  'Visualization view': '可视化视图',
  'Visualization is loading.': '正在加载可视化。',
  'Partial evidence': '部分证据',
  'Evidence unavailable': '证据不可用',
  'must include at least one series': '必须至少包含一个数据系列',
  'series': '数据系列',
  'Recent dates shown. Scroll left for earlier dates.': '当前显示近期日期；向左滚动可查看更早日期。',
  'Data is ready.': '数据已就绪。',
  'Live facts': '实时事实',
  'Live snapshots': '实时快照',
  'loading': '正在加载',
  'updating': '正在更新',
  'unavailable': '不可用',
  'waiting': '等待中',
  'Model calls display controls': '模型调用显示控件',
  'Highest-attention Threads display controls': '关注度最高的对话线程显示控件',
  'aggregate rows': '聚合记录',
  'grouped threads': '分组线程',
  'Percent line chart': '百分比折线图',
  'Percent history. Recent dates are shown first; scroll left for earlier dates.': '百分比历史记录。近期日期优先显示；向左滚动可查看更早日期。',
  'Reload Commands diagnostic snapshot': '重新加载命令诊断快照',
  'Reload Git Interactions diagnostic snapshot': '重新加载 Git 交互诊断快照',
  'unknown · weekly primary signal': '未知 · 每周主要信号',
  'Cache hit %': '缓存命中率',
  'Thread lifecycle': '线程生命周期',
  'Call': '调用',
  'Elapsed': '已经过时间',
  'Context': '上下文',
  'Continuation': '延续调用',
  'Initiator': '发起方',
  'total': '总计',
  'blank': '未指定',
  'max': '最大',
  'ultra': '极高',
  'xhigh': '超高',
};

export const commonZhHansPatterns: ReadonlyArray<ZhHansPattern> = [
  { pattern: /^(.+) table$/u, replace: '$1表格' },
  { pattern: /^([\d,.]+)m ([\d,.]+)s$/u, replace: '$1 分 $2 秒' },
  { pattern: /^([\d,.]+)s$/u, replace: '$1 秒' },
  { pattern: /^Sort by (.+)$/u, replace: (_match, label) => `按${label}排序` },
  { pattern: /^Showing ([\d,.]+) of ([\d,.]+) table rows$/u, replace: '显示 $1 / $2 条表格记录' },
  { pattern: /^Show ([\d,.]+) more rows$/u, replace: '再显示 $1 条记录' },
  { pattern: /^Loaded ([\d,.]+) of ([\d,.]+) available calls$/u, replace: '已加载 $1 / $2 次可用调用' },
  { pattern: /^([\d,.]+) calls analyzed · ([\d,.]+) detail rows cached$/u, replace: '已分析 $1 次调用 · 已缓存 $2 条详情记录' },
  { pattern: /^([\d,.]+) calls available in scope$/u, replace: '当前范围内有 $1 次调用' },
  { pattern: /^([\d,.]+) loaded calls$/u, replace: '已加载 $1 次调用' },
  { pattern: /^([\d,.]+) evidence rows$/u, replace: '$1 条证据记录' },
  { pattern: /^Unknown project ([\d,.]+)$/u, replace: '未知项目 $1' },
  { pattern: /^([\d,.]+) ranked evidence rows$/u, replace: '$1 条已排序证据记录' },
  { pattern: /^Updated (.+)$/u, replace: '更新于 $1' },
  { pattern: /^Loading (.+)\.\.\.$/u, replace: '正在加载$1…' },
  { pattern: /^No (.+) to export$/u, replace: '没有可导出的$1' },
  { pattern: /^Exported ([\d,.]+) (.+)$/u, replace: '已导出 $1 条$2' },
  { pattern: /^(.+) endpoint failed with HTTP ([\d]+)\.$/u, replace: '$1接口请求失败（HTTP $2）。' },
  { pattern: /^Back to (.+)$/u, replace: '返回$1' },
  { pattern: /^Clear (.+)$/u, replace: '清除$1' },
  { pattern: /^Incomplete page evidence: (.+)$/u, replace: '页面证据不完整：$1' },
  { pattern: /^All time analysis uses ([\d,.]+) calls; ([\d,.]+) detail rows cached$/u, replace: '全部时间范围共分析 $1 次调用；已缓存 $2 条详情记录' },
  { pattern: /^Focused pages analyze all ([\d,.]+) calls in scope; ([\d,.]+) call rows are cached for immediate detail views\.$/u, replace: '聚焦页面会分析范围内全部 $1 次调用；已缓存 $2 条调用记录，可立即查看详情。' },
  { pattern: /^([\d,.]+) of ([\d,.]+) modules ready$/u, replace: '$1/$2 个模块已就绪' },
  { pattern: /^([\d,.]+(?:[KMBT])?) cached input tokens$/iu, replace: '$1 个缓存输入token' },
  { pattern: /^([\d,.]+(?:[KMBT])?) cached input$/iu, replace: '$1 个缓存输入token' },
  { pattern: /^(.+) · (.+) · ([\d,.]+(?:[KMBT])?) tokens · ([\d,.]+(?:\.\d+)?)% cache$/iu, replace: '$1 · $2 · $3 个token · 缓存 $4%' },
  { pattern: /^([\d,.]+) matching calls with the same evidence fields as the Calls workspace\.$/u, replace: '$1 次调用符合条件，证据字段与“调用”工作区一致。' },
  { pattern: /^Load more recent calls$/u, replace: '加载更多近期调用' },
  { pattern: /^(.+) line chart$/u, replace: '$1折线图' },
  { pattern: /^(.+) chart$/u, replace: '$1图表' },
  { pattern: /^(.+) history\. Recent dates are shown first; scroll left for earlier dates\.$/u, replace: '$1历史记录。近期日期优先显示；向左滚动可查看更早日期。' },
  { pattern: /^Showing ([\d,.]+) of ([\d,.]+) full-scope thread summaries\.$/u, replace: '显示 $1 / $2 个完整范围线程摘要。' },
  { pattern: /^([\d,.]+) table rows available\.$/u, replace: '可查看 $1 条表格记录。' },
  { pattern: /^(.+) display controls$/u, replace: '$1显示控件' },
  { pattern: /^(.+) modules$/u, replace: '$1模块' },
];
