import type { ZhHansPattern } from './types';

export const corePagesZhHansTranslations: Readonly<Record<string, string>> = {
  // Application shell, navigation, and shared controls.
  'High-level telemetry': '全局用量概览',
  'Root-cause evidence': '根因证据',
  'Context savings': '上下文节省分析',
  'Model-call table': '模型调用明细',
  'Thread efficiency': '线程效率',
  'Allowance intelligence': '限额分析',
  'Cache and cold resumes': '缓存与冷恢复',
  'Technical report': '技术诊断',
  'Generated analyses': '生成的分析报告',
  'Local configuration': '本地配置',
  'Search dashboard': '搜索仪表盘',
  'Search calls, threads, models, diagnostics...': '搜索调用、线程、模型和诊断…',
  'Loaded cached dashboard snapshot': '已加载缓存的仪表盘快照',
  'Refresh cancelled; stored snapshot remains visible': '刷新已取消，仍显示已存储的快照',
  'Copied current view link': '已复制当前视图链接',
  'Copied call investigator link': '已复制调用分析器链接',
  'Copied investigator link': '已复制分析器链接',
  'Copied Calls view link': '已复制“调用”视图链接',
  'Copy unavailable in this browser': '此浏览器无法复制',
  'Investigation preset cleared': '已清除调查预设',
  'Calls filters cleared': '已清除调用筛选条件',
  'Thread filters cleared': '已清除线程筛选条件',
  'Refreshing usage index': '正在刷新用量索引',
  'All history selected; no archived calls are indexed yet': '已选择全部历史记录，但尚未索引归档调用',
  'All calls loaded': '已加载全部调用',
  'Rows to load': '加载记录数',
  'Rows to load slider': '加载记录数滑块',
  'Row loading progress': '记录加载进度',
  'All effort': '全部推理强度',
  'All confidence': '全部置信度',
  'All models': '全部模型',
  'All sources': '全部来源',
  'Exact cost': '精确成本',
  'Estimated cost': '估算成本',
  'Unpriced cost': '未定价成本',
  'Exact credit': '精确点数',
  'Estimated credit': '估算点数',
  'Credit override': '点数费率覆盖值',
  'Missing credit': '缺少点数费率',
  'Exact credit rate': '精确点数费率',
  'Estimated credit mapping': '估算点数映射',
  'User credit override': '用户点数费率覆盖值',
  'Missing credit rate': '缺少点数费率',
  'This week': '本周',
  'This month': '本月',
  'Custom range': '自定义范围',
  'Scope accounting categories': '范围统计分类',
  'Loaded accounting categories': '已加载数据统计分类',
  'To': '去向',
  'Basis': '依据',
  'More filters': '更多筛选条件',
  'Project / cwd': '项目 / 工作目录',
  'Session-linked': '关联会话',
  'Git metadata': 'Git 元数据',
  'Source file': '源文件',
  'Missing source': '缺少来源信息',
  'Start': '开始日期',
  'End': '结束日期',
  'Sort': '排序',
  'Direction': '方向',
  'Ascending': '升序',
  'Descending': '降序',
  'Loading...': '正在加载…',
  'Refreshing...': '正在刷新…',
  'Loading more...': '正在加载更多…',
  'Loading evidence': '正在加载证据',
  'Updating focused rows': '正在更新聚焦记录',
  'Loading focused rows': '正在加载聚焦记录',
  'Focused paged API': '聚焦分页 API',
  'Focused endpoints': '聚焦接口',
  'Partial endpoint evidence': '部分接口证据',
  'Multiple searches use loaded snapshot': '多个搜索条件将使用已加载的快照',
  'Preset uses loaded snapshot': '预设将使用已加载的快照',
  'Source filter uses loaded snapshot': '来源筛选将使用已加载的快照',
  'Risk filter uses loaded snapshot': '风险筛选将使用已加载的快照',
  'This sort uses loaded snapshot': '此排序将使用已加载的快照',
  'Date range invalid': '日期范围无效',
  'Custom date range': '自定义日期范围',
  'not available in filtered view': '筛选后的视图中不可用',
  'not available in payload': '数据中不可用',
  'filtered aggregate rows': '筛选后的聚合记录',
  'local pricing config': '本地定价配置',
  'privacy-safe estimate': '隐私安全估算',
  'loaded calls matching filters': '符合筛选条件的已加载调用',
  'legacy shell filters': '旧版全局筛选条件',
  'active history': '活动记录',
  'all history': '全部历史记录',
  'call rows': '调用记录',
  'settings rows': '设置记录',
  'complete selected scope': '完整的所选范围',
  'healthy cache reuse': '缓存复用良好',
  'cache risk': '缓存风险',
  'static snapshot': '静态快照',
  'no cap': '不设上限',

  // Shared components and environment state.
  'Click opens full investigator. Hover or press Space previews details.': '单击打开完整分析器；悬停或按空格键可预览详情。',
  'Click to inspect details. Double-click or press Enter open full investigator.': '单击查看详情；双击或按 Enter 键打开完整分析器。',
  'Click or press Enter open the full investigator.': '单击或按 Enter 键打开完整分析器。',
  'Local API token present for refresh actions.': '已提供本机 API 令牌，可执行刷新操作。',
  'Static embedded snapshot; live refresh is unavailable.': '当前为静态内嵌快照，无法实时刷新。',
  'Codex credit rates': 'Codex 点数费率',
  'Rate-card error': '费率表错误',
  'Credit rates loaded': '已加载点数费率',
  'No local allowance windows are configured.': '尚未配置本地限额窗口。',
  'cwd redacted': '工作目录已脱敏',
  'project names redacted': '项目名称已脱敏',
  'git remote hidden': 'Git 远程地址已隐藏',
  'relative cwd hidden': '相对工作目录已隐藏',
  'git branch hidden': 'Git 分支已隐藏',
  'tags hidden': '标签已隐藏',
  'Estimated Credits': '估算点数',
  'Estimated Cost': '估算成本',
  'Usage Remaining': '剩余用量',
  'Cache Hit Rate': '缓存命中率',
  'Cache hit rate': '缓存命中率',
  'Cache state': '缓存状态',
  'Cache read': '缓存读取量',
  'Cache/context': '缓存/上下文',
  'mostly_codex': '主要由 Codex 发起',
  'mostly_user': '主要由用户发起',
  'mixed': '混合发起',
  'Stop and summarize the failure mode before retrying commands.': '再次尝试命令前，请先停止操作并总结失败模式。',

  // Overview.
  'Usage summary': '用量摘要',
  'Recommendations': '建议',
  'Selected scope usage metrics': '所选范围的用量指标',
  'No rule-based usage issue stands out': '未发现明显的规则型用量问题',
  'Load calls to establish a usage baseline': '加载调用以建立用量基线',
  'The Overview needs aggregate calls before it can rank evidence or build token accounting.': '“概览”需要先获得聚合调用，才能对证据排序并生成token统计。',
  'Continue monitoring and investigate any workflow that feels unexpectedly expensive.': '继续监控，并调查任何成本异常偏高的工作流。',
  'Load recent calls or all history.': '加载近期调用或全部历史记录。',
  'Review the loaded aggregate evidence in Investigate.': '在“调查分析”中查看已加载的聚合证据。',
  'Focused summary unavailable; showing loaded call rows.': '聚焦摘要不可用，当前显示已加载的调用记录。',
  'Daily token movement': '每日token变化',
  'Scope accounting': '范围统计',
  'Loaded accounting': '已加载数据统计',
  'calls in selected scope': '所选范围内的调用',
  'loaded calls': '已加载调用',
  'Token accounting in scope': '范围内token统计',
  'The four reported token categories across the complete selected data scope.': '完整所选数据范围内日志报告的四类token统计。',
  'Reported type': '报告类型',
  'Input accounting': '输入统计',
  'Generated accounting': '生成内容统计',
  'calls in the selected scope': '所选范围内的调用',
  'One ranked call supports this pattern.': '有 1 次已排序调用支持此模式。',
  'all-history scope': '全部历史记录范围',
  'active-history scope': '活动记录范围',
  'No loaded calls are available for the usage constellation.': '没有可用于用量星图的已加载调用。',
  'Unassigned thread': '未归属线程',
  'Other models': '其他模型',
  'Overview calls': '概览调用',
  'Overview calls display controls': '概览调用显示控件',
  'Overview calls ranked list': '概览调用排序列表',

  // Calls and call investigator.
  'Calls': '调用',
  'Evidence explorer': '证据浏览器',
  'Find expensive, cold, or context-heavy calls and move directly into their evidence.': '查找高成本、冷缓存或上下文负载较高的调用，并直接查看相关证据。',
  'Copy view': '复制视图链接',
  'Model calls': '模型调用',
  'Call filters': '调用筛选器',
  'Search calls': '搜索调用',
  'Search calls, cwd, projects, models...': '搜索调用、工作目录、项目和模型…',
  'Confidence': '置信度',
  'Confidence filter': '置信度筛选器',
  'Time filter': '时间筛选器',
  'Source': '来源',
  'Source filter': '来源筛选器',
  'Start date': '开始日期',
  'End date': '结束日期',
  'Sort calls': '调用排序',
  'Sort direction': '排序方向',
  'Newest calls': '最新调用',
  'Longest duration': '耗时最长',
  'Longest gap': '间隔最长',
  'Needs attention': '需要关注',
  'Thread name': '线程名称',
  'Usage Over Time': '用量趋势',
  'Cost by Model': '按模型统计成本',
  'Estimated USD': '估算美元成本',
  'Cache Hit Rate Over Time': '缓存命中率趋势',
  'Cache %': '缓存比例',
  'Usage patterns': '用量模式',
  'Raw context gated': '原始上下文受控',
  'Call Drill-Down': '调用深入分析',
  'No matching call': '没有匹配的调用',
  'Not available': '不可用',
  'Not reported': '未报告',
  'No aggregate row matches the active filters.': '没有符合当前筛选条件的聚合记录。',
  'Aggregate only': '仅聚合数据',
  'Call drill-down sections': '调用深入分析区域',
  'Total tokens': 'token总数',
  'fresh billed input': '新增计费输入',
  'Fresh share': '新增输入占比',
  'Loaded thread calls': '已加载的线程调用',
  'Thread tokens': '线程token数',
  'loaded aggregate rows': '已加载的聚合记录',
  'Thread cost': '线程成本',
  'estimated aggregate': '聚合估算',
  'Avg cache': '平均缓存比例',
  'Initiated by': '发起方',
  'Initiator reason': '发起原因',
  'Previous gap': '与上次调用的间隔',
  'Project path': '项目路径',
  'Working directory': '工作目录',
  'Git remote': 'Git 远程地址',
  'Git hash': 'Git 哈希',
  'Token composition': 'token构成',
  'Cache delta readout': '缓存变化解读',
  'Accounting Snapshot': '统计快照',
  'pricing, credits, and cache savings': '定价、点数与缓存节省',
  'Use this readout to decide whether the aggregate call needs deeper raw-context investigation.': '根据此解读判断是否需要进一步调查该聚合调用的原始上下文。',
  'Call Narrative': '调用解读',
  'Call Source': '调用来源',
  'Direct thread': '直接线程',
  'No model mix': '没有模型构成数据',
  'no model mix': '没有模型构成数据',
  'not reported': '未报告',
  'no parent session': '没有父会话',
  'aggregate inference': '聚合推断',
  'estimated pricing': '估算定价',
  'configured pricing': '已配置定价',
  'fast candidate': '可快速处理',
  'normal throughput': '吞吐量正常',
  'Investigation Readout': '调查解读',
  'Aggregate + on-demand evidence': '聚合数据与按需证据',
  'No aggregate recommendation': '没有聚合建议',
  'Compared previous call': '已与上一次调用比较',
  'This call is outside the loaded snapshot. Serve the dashboard with its localhost API token to hydrate it.': '此调用不在已加载的快照中。请使用本机 API 令牌运行仪表盘，以补载其数据。',
  'Loading call detail from localhost...': '正在从本机服务加载调用详情…',
  'Selected call is not present in the loaded dashboard rows.': '已加载的仪表盘记录中没有所选调用。',
  'No aggregate call rows are loaded.': '尚未加载聚合调用记录。',
  'Hydrated live': '已实时补载',
  'Hydrated from /api/call': '已从 /api/call 补载',
  'Record outside loaded snapshot': '记录位于已加载快照之外',
  'Position: hydrated live record outside loaded snapshot': '位置：已实时补载，记录位于已加载快照之外',
  'Token Accounting': 'token统计',
  'Exact aggregate row fields': '精确的聚合记录字段',
  'Cache Accounting': '缓存统计',
  'Derived from adjacent aggregate call': '根据相邻聚合调用推导',
  'Context Attribution': '上下文归因',
  'Local metadata only': '仅本地元数据',
  'Thread Context': '线程上下文',
  'Raw Evidence': '原始证据',
  'Explicit localhost request only': '仅在明确请求本机服务时加载',
  'Context mode': '上下文模式',
  'Context entries': '上下文条目',
  'Side panel context mode': '侧栏上下文模式',
  'Side panel context entries': '侧栏上下文条目',
  'Visible chars': '可见字符数',
  'redacted local text': '已脱敏的本地文本',
  'Visible tokens': '可见token数',
  'Older omitted': '已省略较早条目',
  'entry budget': '条目预算',
  'Thread calls': '线程调用数',
  'Cache risks': '缓存风险',
  'weak reuse or flagged': '复用较弱或已标记',
  'Context pressure': '上下文压力',
  '>=60% context window': '上下文窗口占用不低于 60%',
  'Models in thread': '线程中的模型',
  'Effort mix': '推理强度构成',
  'Enabling localhost context API...': '正在启用本机上下文 API…',
  'Context API enabled. Load this call when ready.': '上下文 API 已启用，可以加载此调用。',
  'Context API did not enable.': '未能启用上下文 API。',
  'Loading selected-turn evidence...': '正在加载所选轮次的证据…',
  'Loading full turn analysis...': '正在加载完整轮次分析…',
  'Loading older context...': '正在加载更早的上下文…',
  'Loading omitted tool output...': '正在加载已省略的工具输出…',
  'Loading compacted replacement...': '正在加载压缩后的替换内容…',
  'local evidence': '本地证据',
  '[no visible text]': '[没有可见文本]',
  '[no visible replacement text]': '[没有可见的替换文本]',
  'Raw context is never embedded in the dashboard HTML. This view reads the selected local JSONL turn only after an explicit request.': '原始上下文绝不会嵌入仪表盘 HTML；只有明确请求后，此视图才会读取本地 JSONL 中所选轮次的内容。',
  'Raw context is read from the local JSONL source only after this explicit action and is not embedded in static dashboard HTML.': '只有执行此明确操作后才会从本地 JSONL 源读取原始上下文，并且不会将其嵌入静态仪表盘 HTML。',
  'No visible evidence entries returned for this call.': '此调用没有返回可见的证据条目。',
  'Static file mode cannot read local JSONL context. Use serve-dashboard with the context API enabled.': '静态文件模式无法读取本地 JSONL 上下文。请运行 serve-dashboard 并启用上下文 API。',
  'Context loading requires the localhost dashboard server API token.': '加载上下文需要本机仪表盘服务器的 API 令牌。',
  'Context API is available but off. Enable it here before loading selected-turn evidence.': '上下文 API 可用但尚未启用；请先在此启用，再加载所选轮次的证据。',
  'Context API is enabled. Load selected-turn evidence from the local JSONL source only when needed.': '上下文 API 已启用；仅在需要时从本地 JSONL 源加载所选轮次的证据。',
  'Local JSONL context loaded on demand.': '已按需加载本地 JSONL 上下文。',
  'No previous call is loaded in resolved thread, call-to-call deltas unavailable.': '解析出的线程中未加载上一次调用，因此无法计算调用间变化。',
  'Token accounting broadly stable compared previous call in resolved thread.': '与解析出的线程中上一次调用相比，token统计整体稳定。',
  'Evidence is not loaded yet. Aggregate token counts are exact, but visible-context attribution needs runtime evidence.': '尚未加载证据。聚合token数是精确值，但可见上下文归因需要运行时证据。',
  'Fast serialized estimate only; full serialized grouping deferred.': '当前仅提供快速序列化估算；完整的序列化分组尚未执行。',
  'Compare previous call, then inspect loaded evidence see fresh context was sent after cache miss.': '先与上一次调用比较，再检查已加载证据，确认缓存未命中后发送了哪些新增上下文。',
  'Inspect most recent evidence entries first; spike is in fresh uncached input, not cached history.': '请先检查最新的证据条目；峰值来自新增的未缓存输入，而不是缓存历史。',
  'Use delta cards to locate whether change came from cached input, uncached input, or output/reasoning.': '使用变化卡片判断差异来自缓存输入、未缓存输入，还是输出/推理。',
  'Use loaded evidence if aggregate totals are not enough understand this isolated call.': '如果聚合总量不足以解释此调用，请查看已加载证据。',
  'visible-token estimate': '可见token估算',
  'Raw context is gated': '原始上下文受控',
  'Include compaction history': '包含压缩历史',
  'Record id': '记录 ID',
  'Entry tokens': '条目token数',
  'Session tokens': '会话token数',
  'Tool output': '工具输出',
  'Evidence entry metadata': '证据条目元数据',
  'Elapsed since selected turn start': '自所选轮次开始后的耗时',
  'Gap since previous evidence entry': '与上一条证据的间隔',
  'Duration reported by this event': '此事件报告的耗时',
  'Token usage reported for this evidence entry': '此证据条目报告的token用量',
  'Cumulative token usage reported by this evidence entry': '此证据条目报告的累计token用量',
  'Compaction replacement history is available for this entry': '此条目有可用的压缩替换历史',
  'Tool output omitted until explicitly requested': '工具输出已省略，明确请求后才会加载',
  'No previous call': '没有上一次调用',
  'No previous call loaded for delta comparison.': '尚未加载可用于变化对比的上一次调用。',
  'No previous aggregate call available for cache delta accounting.': '没有可用于缓存变化统计的上一次聚合调用。',
  'Some prefix reused cache, but a meaningful share of input was fresh or reserialized.': '部分前缀复用了缓存，但仍有相当比例的输入为新增内容或重新序列化内容。',
  'Cache accounting is stable versus the previous aggregate call.': '与上一次聚合调用相比，缓存统计基本稳定。',
  'Compare the previous call, then inspect loaded evidence to see what fresh context was sent after the cache miss.': '先与上一次调用比较，再检查已加载证据，确认缓存未命中后发送了哪些新增上下文。',
  'Use delta cards to locate whether the change came from cached input, uncached input, or output/reasoning.': '使用变化卡片判断差异来自缓存输入、未缓存输入，还是输出/推理。',
  'Use loaded evidence if aggregate totals are not enough to understand this isolated call.': '如果聚合总量不足以解释此调用，请查看已加载证据。',
  'Cache Accounting Delta': '缓存统计变化',
  'Not loaded yet': '尚未加载',
  'Runtime evidence': '运行时证据',
  'exact aggregate row': '精确聚合记录',
  'serialized-breakdown deferred': '序列化明细尚未生成',
  'uncached input minus visible estimate': '未缓存输入减去可见内容估算值',
  'serialized upper bound minus visible estimate': '序列化上限减去可见内容估算值',
  'not covered by serialized upper bound': '序列化上限未覆盖的部分',
  'No serialized evidence groups returned.': '没有返回序列化证据分组。',
  'Configure pricing': '配置定价',
  'Compare fresh input': '比较新增输入',
  'Inspect thread timeline': '查看线程时间线',
  'Review reasoning effort': '检查推理强度',
  'Use aggregate first': '先查看聚合数据',
  'High reported context use.': '报告的上下文占用较高。',
  'Reasoning output exceeds visible output.': '推理输出超过可见输出。',
  'Review cost and credit impact before loading raw context.': '加载原始上下文前，请先检查成本和点数影响。',
  'No aggregate efficiency flag on this row.': '此记录没有聚合效率标记。',
  'Call Decision': '调用决策',
  'cold or weak cache': '缓存未命中或复用较弱',
  'partial cache reuse': '部分缓存复用',
  'No related calls': '没有相关调用',
  'Highest Cost Threads': '成本最高的线程',
  'Context Bloat': '上下文膨胀',
  'Cache Misses': '缓存未命中',
  'Pricing Gaps': '定价缺口',
  'Reasoning Spike': '推理峰值',
  'Output Tokens': '输出token',
  'Est. Cost': '估算成本',
  'Codex Credits': 'Codex 点数',
  'Effort Mix': '推理强度构成',

  // Explore workspaces.
  'Explore workspace': '浏览工作区',
  'File evidence': '文件证据',
  'Tool evidence': '工具证据',
  'File filters': '文件筛选器',
  'Tool filters': '工具筛选器',
  'Search file evidence': '搜索文件证据',
  'Search tool evidence': '搜索工具证据',
  'Search path labels and exact path hashes...': '搜索路径标签和精确路径哈希…',
  'Search tools, categories, and actions...': '搜索工具、类别和操作…',
  'File evidence results': '文件证据结果',
  'Tool evidence results': '工具证据结果',
  'File evidence results display controls': '文件证据结果显示控件',
  'Tool evidence results display controls': '工具证据结果显示控件',
  'File evidence results ranked list': '文件证据结果排序列表',
  'Tool evidence results ranked list': '工具证据结果排序列表',
  'File inspector': '文件检查器',
  'Tool inspector': '工具检查器',
  'No evidence selected': '尚未选择证据',
  'No representative call': '没有代表性调用',
  'Select a file row to inspect its aggregate activity.': '选择一条文件记录以查看其聚合活动。',
  'Select a tool row to inspect its aggregate evidence.': '选择一条工具记录以查看其聚合证据。',
  'Find repeated reads and modifications using local aggregate path labels and stable path hashes.': '利用本地聚合路径标签和稳定路径哈希查找重复读取与修改。',
  'Rank tool and function activity by associated token pressure, then inspect the calls behind each pattern.': '按关联token压力对工具和函数活动排序，再查看每种模式背后的调用。',
  'No file evidence is available in the stored diagnostic snapshots.': '已存储的诊断快照中没有文件证据。',
  'No tool evidence matches the active filters.': '没有符合当前筛选条件的工具证据。',
  'File evidence requires the localhost dashboard server.': '文件证据需要本机仪表盘服务器。',
  'Tool evidence requires the localhost dashboard server.': '工具证据需要本机仪表盘服务器。',
  'Local server required': '需要本机服务器',
  'Updating file snapshots': '正在更新文件快照',
  'Loading file snapshots': '正在加载文件快照',
  'File snapshots unavailable': '文件快照不可用',
  'Stored diagnostic snapshots': '已存储的诊断快照',
  'No file snapshots loaded': '尚未加载文件快照',
  'Updating tool facts': '正在更新工具事实',
  'Loading tool facts': '正在加载工具事实',
  'Tool facts unavailable': '工具事实不可用',
  'Focused diagnostic API': '聚焦诊断 API',
  'No tool facts loaded': '尚未加载工具事实',
  'Path Hash': '路径哈希',
  'Path Label': '路径标签',
  'Read Events': '读取事件数',
  'Read Output': '读取输出',
  'Allocated Read Output Tokens': '分配的读取输出token数',
  'Modification Events': '修改事件数',
  'Path hash': '路径哈希',
  'Read evidence': '读取证据',
  'Modification evidence': '修改证据',
  'Read events': '读取事件数',
  'Read output': '读取输出',
  'Open evidence call': '打开证据调用',
  'Path hashes provide stable local identity for repeated rediscovery without placing raw file content in the aggregate response.': '路径哈希可为重复发现提供稳定的本地标识，同时避免在聚合响应中包含原始文件内容。',
  'Uncached Input Tokens': '未缓存输入token数',
  'Cache Percent': '缓存比例',
  'Largest Call': '最大调用',
  'Associated Calls': '关联调用数',
  'Associated calls': '关联调用',
  'Cache reuse': '缓存复用率',
  'Largest call': '最大调用',
  'Open largest call': '打开最大调用',
  'Supporting calls': '支撑调用',
  'No supporting call rows are loaded for this tool fact.': '尚未加载此工具事实对应的支撑调用记录。',
  'tool activity': '工具活动',
  'Unknown path': '未知路径',
  'Visible columns': '可见列',
  'No evidence matches the current filters.': '没有符合当前筛选条件的证据。',

  // Threads.
  'Threads': '线程',
  'Thread Leaderboard': '线程排行榜',
  'Thread leaderboard': '线程排行榜',
  'Compare work units, follow lifecycle pressure, and open supporting calls without leaving the evidence surface.': '比较工作单元、跟踪生命周期压力，并在证据页面中直接打开支撑调用。',
  'Thread filters': '线程筛选器',
  'Search threads': '搜索线程',
  'Search threads, risks, token totals...': '搜索线程、风险和token总量…',
  'Cold risk': '冷恢复风险',
  'All risks': '全部风险',
  'Cache frontier': '缓存效率前沿',
  'Updating thread calls': '正在更新线程调用',
  'Updating focused threads': '正在更新聚焦线程',
  'Loading focused threads': '正在加载聚焦线程',
  'Reset thread view': '重置线程视图',
  'Loading thread summaries and selected calls': '正在加载线程摘要和所选调用',
  'Thread evidence view': '线程证据视图',
  'Thread evidence': '线程证据',
  'Thread evidence display controls': '线程证据显示控件',
  'Thread evidence ranked list': '线程证据排序列表',
  'Export thread calls': '导出线程调用',
  'Reset view': '重置视图',
  'Selected Thread': '所选线程',
  'No matching thread': '没有匹配的线程',
  'No grouped thread matches the active filters.': '没有符合当前筛选条件的分组线程。',
  'Thread Calls': '线程调用',
  'No loaded calls': '没有已加载的调用',
  'Loading more calls': '正在加载更多调用',
  'No loaded aggregate call rows belong to this thread.': '此线程没有已加载的聚合调用记录。',
  'Turns visible': '可见轮次数',
  'Total duration': '总耗时',
  'Average gap': '平均间隔',
  'Cached / uncached input': '缓存 / 未缓存输入',
  'Peak context': '上下文峰值',
  'Risk Mix': '风险构成',
  'Productivity': '生产效率',
  'Thread Status': '线程状态',
  'Pricing status': '定价状态',
  'Credit status': '点数状态',
  'Cache ratio': '缓存比例',
  'Max context use': '最大上下文占用',
  'Thread Impact': '线程影响',
  'Codex credits': 'Codex 点数',
  'Allowance impact': '限额影响',
  'Attention score': '关注度评分',
  'Cost per call': '单次调用成本',
  'Thread Lifecycle': '线程生命周期',
  'Subagent before spike': '峰值前出现子代理',
  'Aggregate trend': '聚合趋势',
  'First expensive turn': '首次高成本轮次',
  'Largest token jump': '最大token增幅',
  'Cache trend': '缓存趋势',
  'Context trend': '上下文趋势',
  'Relationships': '关系',
  'Loaded aggregate links': '已加载的聚合关联',
  'Spawned from': '派生自',
  'Subagent calls': '子代理调用',
  'Auto-review calls': '自动审查调用',
  'Attached calls': '附加调用',
  'Spawned threads': '派生线程',
  'Spawned child calls': '派生子调用',
  'Thread Fields': '线程字段',
  'Latest activity': '最近活动',
  'Loaded calls': '已加载调用',
  'Efficiency signals': '效率信号',
  'Model mix': '模型构成',
  'Sort thread calls': '线程调用排序',
  'Sort thread calls direction': '线程调用排序方向',
  'Newest': '最新',
  'Most tokens': 'token最多',
  'Highest cost': '成本最高',
  'Lowest cache': '缓存比例最低',
  'Avg Gap': '平均间隔',
  'Cost / Call': '单次调用成本',
  'Cold Resume Risk': '冷恢复风险',
  'Latest': '最近活动',
  'Turns': '轮次',
  'High': '高',
  'Medium': '中',
  'Low': '低',
  'Official match': '官方精确匹配',
  'Mixed': '混合匹配',
  'Configured': '已配置',
  'Estimated mapping': '估算映射',
  'No mapped rate': '没有匹配的费率',
  'No price': '无定价',
  'Cache Drop': '缓存下降',
  'Cache Risk': '缓存风险',
  'Context Heavy': '上下文负载高',
  'Elevated Context': '上下文偏高',
  'Elevated Context Use': '上下文占用偏高',
  'Estimated Pricing': '估算定价',
  'Expensive Low Output Call': '高成本低输出调用',
  'High Context Use': '上下文占用高',
  'High Cost': '高成本',
  'High Estimated Cost': '估算成本高',
  'High Reasoning Share': '推理占比高',
  'Large Thread': '大型线程',
  'Low Cache': '缓存偏低',
  'Low Cache Reuse': '缓存复用率低',
  'Low Output': '输出偏低',
  'Pricing Gap': '定价缺口',
  'Subagent Attribution': '子智能体归因',
  'Review context growth': '检查上下文增长',
  'Check cache drop': '检查缓存下降',
  'Compare subagent calls': '比较子代理调用',
  'Review recommendations': '查看建议',
  'Load thread calls': '加载线程调用',
  'Cache efficiency frontier': '缓存效率前沿',
  'Threads further right carry more input; threads lower on the plot reuse less of it.': '越靠右的线程输入量越大；图中位置越低，缓存复用越少。',
  'No threads match the current scope.': '没有符合当前范围的线程。',
  'Credits and cost remain estimates when exact rate metadata is unavailable.': '如果没有精确费率元数据，点数和成本仍为估算值。',
  'Use arrow keys to move between threads; press Enter to synchronize the selected row.': '使用方向键在线程间移动；按 Enter 键同步所选记录。',
  'Cache efficiency by thread': '各线程缓存效率',
  '35% review floor': '35% 检查阈值',
  'Context pressure and cache reuse across the selected thread.': '所选线程的上下文压力与缓存复用情况。',
  'Context-window evidence is unavailable for this thread.': '此线程没有可用的上下文窗口证据。',
  'No thread selected': '尚未选择线程',
  'Lifecycle labels are inferred from aggregate timing, cache, and context fields.': '生命周期标签根据聚合耗时、缓存和上下文字段推断。',
  'Use left and right arrow keys to move through calls in lifecycle order.': '使用左右方向键按生命周期顺序浏览调用。',
  'Selected thread lifecycle calls': '所选线程的生命周期调用',
  'Lifecycle event': '生命周期事件',
  'Minutes since first call': '距首次调用的分钟数',
  'Context / cache': '上下文 / 缓存',
  'No loaded high-token thread falls below the 35 percent cache review floor.': '没有已加载的高token线程低于 35% 的缓存检查阈值。',
  'the selected thread': '所选线程',
  'Thread start': '线程开始',
  'Cold resume': '冷恢复',
  'Warm continuation': '热缓存延续',
};

export const corePagesZhHansPatterns: ReadonlyArray<ZhHansPattern> = [
  { pattern: /^(Today|This week|Last 7 days|This month): (\d{4}-\d{2}-\d{2}) to (\d{4}-\d{2}-\d{2})$/u, replace: (_match, preset, start, end) => `${datePresetZhHans(preset)}：${start} 至 ${end}` },
  { pattern: /^Custom: (\d{4}-\d{2}-\d{2}) to (\d{4}-\d{2}-\d{2})$/u, replace: '自定义：$1 至 $2' },
  { pattern: /^Custom: from (\d{4}-\d{2}-\d{2})$/u, replace: '自定义：从 $1 开始' },
  { pattern: /^Custom: through (\d{4}-\d{2}-\d{2})$/u, replace: '自定义：截至 $1' },
  // Shell progress and history counts.
  { pattern: /^Auto refresh every ([\d,.]+)s$/u, replace: '每 $1 秒自动刷新' },
  { pattern: /^All history includes ([\d,.]+) archived calls$/u, replace: '全部历史记录包含 $1 次归档调用' },
  { pattern: /^Active sessions only; ([\d,.]+) archived calls hidden$/u, replace: '仅活动会话；已隐藏 $1 次归档调用' },
  { pattern: /^([\d,.]+) detail rows? cached$/u, replace: '已缓存 $1 条详情记录' },
  { pattern: /^([\d,.]+) loaded \/ ([\d,.]+) total$/u, replace: '已加载 $1 / 共 $2 条' },
  { pattern: /^([\d,.]+) of ([\d,.]+) evidence rows loaded$/u, replace: '已加载 $1 / $2 条证据记录' },
  { pattern: /^([\d,.]+) recent rows$/u, replace: '$1 条近期记录' },
  { pattern: /^([\d,.]+)% loaded$/u, replace: '已加载 $1%' },
  { pattern: /^(Loading|Refreshing) (24 hours|7 days|recent rows|all time)\.\.\.$/u, replace: (_match, action, scope) => `${action === 'Refreshing' ? '正在刷新' : '正在加载'}${scopeZhHans(scope)}…` },
  { pattern: /^Refreshing index for (24 hours|7 days|recent rows|all time)\.\.\.$/u, replace: (_match, scope) => `正在刷新${scopeZhHans(scope)}的索引…` },
  { pattern: /^(Cache hit; |Refreshed index; )?[Ll]oaded ([\d,.]+) of ([\d,.]+) calls from (24 hours|7 days|recent rows|all time)$/u, replace: (_match, prefix, loaded, total, scope) => `${refreshPrefixZhHans(prefix)}已从${scopeZhHans(scope)}加载 ${loaded} / ${total} 次调用` },
  { pattern: /^(Cache hit; |Refreshed index; )?(24 hours|7 days|recent rows|all time) analysis ready across ([\d,.]+) calls; ([\d,.]+) detail rows cached$/iu, replace: (_match, prefix, scope, total, cached) => `${refreshPrefixZhHans(prefix)}${scopeZhHans(scope.toLowerCase())}分析已就绪，共 ${total} 次调用；已缓存 ${cached} 条详情记录` },
  { pattern: /^(.+) Stored snapshot kept at (.+)$/u, replace: '$1 已保留 $2 的存储快照' },
  { pattern: /^Metadata mode: (.+)$/u, replace: '元数据模式：$1' },
  { pattern: /^Config error: (.+)$/u, replace: '配置错误：$1' },
  { pattern: /^Rate-card error: (.+)$/u, replace: '费率表错误：$1' },
  { pattern: /^Deduped · ([\d,.]+) copied excluded$/u, replace: '已去重 · 排除 $1 条重复记录' },
  { pattern: /^Billable totals use ([\d,.]+) canonical rows while preserving ([\d,.]+) physical source rows\.$/u, replace: '计费总量使用 $1 条规范记录，同时保留 $2 条物理来源记录。' },

  // Overview summaries and visualization narration.
  { pattern: /^([\d,.]+) detailed rows available$/u, replace: '有 $1 条详情记录可用' },
  { pattern: /^([\d,.]+) daily buckets are available, with the visible window favoring the most recent ([\d,.]+)\.$/u, replace: '共有 $1 个每日时间桶，当前视图优先显示最近 $2 个。' },
  { pattern: /^([\d,.]+) (loaded calls|calls in selected scope|calls in the selected scope)$/u, replace: (_match, count, scope) => `${count} 次${scope === 'loaded calls' ? '已加载调用' : '所选范围内调用'}` },
  { pattern: /^([\d,.]+) (loaded calls|calls in selected scope|calls in the selected scope) include ([\d,.]+) percent cached input reuse\.$/u, replace: (_match, count, scope, percent) => `${scope === 'loaded calls' ? '已加载的' : '所选范围内的'} ${count} 次调用中，缓存输入复用率为 ${percent}%。` },
  { pattern: /^([\d,.]+) ranked calls support this pattern\.$/u, replace: '有 $1 次已排序调用支持此模式。' },
  { pattern: /^((?:low|medium|high|xhigh|ultra|max) x[\d,]+(?:, (?:low|medium|high|xhigh|ultra|max) x[\d,]+)*)$/u, replace: (_match, summary) => effortSummaryZhHans(summary) },
  { pattern: /^([\d,.]+(?:[KMBT])?) at (.+)$/iu, replace: '$1，发生于 $2' },
  { pattern: /^(.+) · Call ([\d,.]+)$/u, replace: '$1 · 第 $2 次调用' },
  { pattern: /^([\d,.]+(?:\.\d+)?) credits \((Official match|Mixed|Configured|Estimated mapping|No mapped rate|No price)\)$/u, replace: (_match, credits, status) => `${credits} 点（${threadStatusZhHans(status)}）` },
  { pattern: /^([\d,.]+(?:[KMBT])?) tokens - ([\d,.]+(?:\.\d+)?)% cache - (.+)$/iu, replace: '$1 个token - 缓存 $2% - $3' },
  { pattern: /^([\d,.]+(?:[KMBT])?) tokens - ([\d,.]+(?:\.\d+)?)% cache$/iu, replace: '$1 个token - 缓存 $2%' },
  { pattern: /^Context ([\d,.]+(?:\.\d+)?)%$/iu, replace: '上下文 $1%' },
  { pattern: /^Prev ([\d,.]+)m ([\d,.]+)s$/iu, replace: '距上次 $1 分 $2 秒' },
  { pattern: /^Prev ([\d,.]+)s$/iu, replace: '距上次 $1 秒' },
  { pattern: /^Prev (.+)$/iu, replace: '距上次 $1' },
  { pattern: /^(.+) initiated$/iu, replace: '$1 发起' },
  { pattern: /^(.+) is the clearest current signal$/u, replace: '当前最明确的信号是：$1' },
  { pattern: /^([\d,.]+) representative calls from ([\d,.]+) loaded calls$/u, replace: '从 $2 次已加载调用中选取 $1 次代表性调用' },
  { pattern: /^The constellation plots ([\d,.]+) loaded calls\. The largest plotted call used ([\d,.]+) tokens\. The lowest plotted cache reuse was ([\d,.]+) percent\.$/u, replace: '星图展示了 $1 次已加载调用。图中最大调用使用 $2 个token，最低缓存复用率为 $3%。' },
  { pattern: /^The constellation plots ([\d,.]+) representative calls from ([\d,.]+) loaded calls\. The largest plotted call used ([\d,.]+) tokens\. The lowest plotted cache reuse was ([\d,.]+) percent\.$/u, replace: '星图从 $2 次已加载调用中展示 $1 次代表性调用。图中最大调用使用 $3 个token，最低缓存复用率为 $4%。' },

  // Calls, evidence, and context counts. Captured labels and identifiers are preserved verbatim.
  { pattern: /^Showing ([\d,.]+) of ([\d,.]+) aggregate rows$/u, replace: '显示 $1 / $2 条聚合记录' },
  { pattern: /^([\d,.]+) project\/cwd rows$/u, replace: '$1 条项目/工作目录记录' },
  { pattern: /^([\d,.]+) session-linked rows$/u, replace: '$1 条会话关联记录' },
  { pattern: /^([\d,.]+) git rows$/u, replace: '$1 条 Git 记录' },
  { pattern: /^([\d,.]+) source-file rows$/u, replace: '$1 条源文件记录' },
  { pattern: /^([\d,.]+) rows missing source$/u, replace: '$1 条缺少来源信息的记录' },
  { pattern: /^([\d,.]+) project, ([\d,.]+) session, ([\d,.]+) git$/u, replace: '项目 $1 条，会话 $2 条，Git $3 条' },
  { pattern: /^Preset: (Highest Cost Threads|Context Bloat|Cache Misses|Pricing Gaps|Codex Credits|Reasoning Spike)$/u, replace: (_match, preset) => `预设：${presetZhHans(preset)}` },
  { pattern: /^Exported ([\d,.]+) calls$/u, replace: '已导出 $1 次调用' },
  { pattern: /^Exported ([\d,.]+) loaded calls$/u, replace: '已导出 $1 次已加载调用' },
  { pattern: /^([\d,.]+) of ([\d,.]+) loaded calls$/u, replace: '第 $1 次，共 $2 次已加载调用' },
  { pattern: /^([\d,.]+) loaded related calls$/u, replace: '已加载 $1 次相关调用' },
  { pattern: /^selected ([\d,.]+) of ([\d,.]+)$/u, replace: '已选择第 $1 个，共 $2 个' },
  { pattern: /^Call ([\d,.]+) of ([\d,.]+)$/u, replace: '调用 $1 / $2' },
  { pattern: /^Entry ([\d,.]+)$/u, replace: '条目 $1' },
  { pattern: /^line ([\d,.]+)$/u, replace: '第 $1 行' },
  { pattern: /^Show first ([\d,.]+) entries$/u, replace: '显示前 $1 个条目' },
  { pattern: /^Show all ([\d,.]+) returned entries$/u, replace: '显示返回的全部 $1 个条目' },
  { pattern: /^Replacement item ([\d,.]+)$/u, replace: '替换项 $1' },
  { pattern: /^([\d,.]+) replacement entries$/u, replace: '$1 个替换条目' },
  { pattern: /^([\d,.]+(?:[KMBT])?) total · ([\d,.]+(?:[KMBT])?) uncached$/iu, replace: '共 $1 个 · 未缓存 $2 个' },
  { pattern: /^([\d,.]+) older entries omitted\.$/u, replace: '已省略 $1 个较早条目。' },
  { pattern: /^([\d,.]+) chars over budget omitted\.$/u, replace: '已省略超出预算的 $1 个字符。' },
  { pattern: /^Source: (.+)\.$/u, replace: '来源：$1。' },
  { pattern: /^Evidence request failed: (.+)$/u, replace: '证据请求失败：$1' },
  { pattern: /^Evidence analyzed: ([\d,.]+) selected-turn entries, ([\d,.]+) visible redacted chars, ([\d,.]+) visible tokens\.(.*)$/u, replace: '已分析证据：所选轮次包含 $1 个条目、$2 个可见脱敏字符和 $3 个可见token。$4' },
  { pattern: /^Serialized local upper bound: ([\d,.]+) tokens\.$/u, replace: '本地序列化上限：$1 个token。' },
  { pattern: /^Position: (.+)$/u, replace: '位置：$1' },
  { pattern: /^([\d,.]+) analyzed chars$/u, replace: '已分析 $1 个字符' },
  { pattern: /^([\d,.]+) raw JSON chars$/u, replace: '$1 个原始 JSON 字符' },
  { pattern: /^([\d,.]+) raw lines$/u, replace: '$1 行原始内容' },
  { pattern: /^([\d,.]+) credits counted$/u, replace: '计入 $1 点' },
  { pattern: /^([\d,.]+) credits$/u, replace: '$1 点' },
  { pattern: /^([\d,.]+(?:[KMBT])?) uncached input with weak cache reuse\.$/iu, replace: '$1 个未缓存输入token，缓存复用较弱。' },
  { pattern: /^Fresh input rose by ([\d,.]+) while cached input fell by ([\d,.]+); classic cache-drop profile\.$/u, replace: '新增输入增加 $1，而缓存输入减少 $2；这是典型的缓存下降特征。' },
  { pattern: /^Fresh input increased by ([\d,.]+) from previous call; inspect evidence new files, tool results, or rewritten context\.$/u, replace: '与上一次调用相比，新增输入增加 $1；请检查证据中的新文件、工具结果或重写的上下文。' },
  { pattern: /^Fresh input fell by ([\d,.]+) while cached input increased, so this call reused context more efficiently previous one\.$/u, replace: '新增输入减少 $1，同时缓存输入增加，因此此调用比上一次更高效地复用了上下文。' },
  { pattern: /^Cache reuse is healthy; focus on ([\d,.]+) uncached tokens (?:were|that were) still billed as fresh input\.$/u, replace: '缓存复用良好；但仍有 $1 个未缓存token按新增输入计费，建议重点检查。' },
  { pattern: /^Uncached input: ([+\-\d,.]+)\. Cached input: ([+\-\d,.]+)\. Cache ratio: ([+\-\d,.]+pp)\.$/u, replace: '未缓存输入：$1。缓存输入：$2。缓存比例：$3。' },
  { pattern: /^Uncached input rose by ([\d,.]+) while cached input fell by ([\d,.]+)\.$/u, replace: '未缓存输入增加 $1，同时缓存输入减少 $2。' },
  { pattern: /^Uncached input increased by ([\d,.]+) versus the previous aggregate call\.$/u, replace: '与上一次聚合调用相比，未缓存输入增加 $1。' },
  { pattern: /^Uncached input decreased by ([\d,.]+) while cached input increased\.$/u, replace: '未缓存输入减少 $1，同时缓存输入增加。' },
  { pattern: /^Signals: (.+)$/u, replace: '信号：$1' },
  { pattern: /^Open call row in investigator for (.+)$/u, replace: '在分析器中打开调用记录：$1' },
  { pattern: /^Open investigator for latest call in (.+)$/u, replace: '在分析器中打开该线程的最新调用：$1' },
  { pattern: /^Copy link for latest call in (.+)$/u, replace: '复制该线程最新调用的链接：$1' },
  { pattern: /^No loaded call available for (.+)$/u, replace: '没有可用于以下对象的已加载调用：$1' },
  { pattern: /^Open investigator for thread call (.+)$/u, replace: '在分析器中打开线程调用：$1' },
  { pattern: /^Copy link for thread call (.+)$/u, replace: '复制线程调用链接：$1' },
  { pattern: /^Context use (.+)$/u, replace: '上下文占用：$1' },

  // Explore actions preserve tool names and path labels exactly.
  { pattern: /^([\d,.]+) reads · ([\d,.]+(?:[KMBT])?) output · ([\d,.]+) modifications$/iu, replace: '读取 $1 次 · 输出 $2 个token · 修改 $3 次' },
  { pattern: /^([\d,.]+(?:[KMBT])?) uncached · ([\d,.]+) calls · ([\d,.]+)% cache$/iu, replace: '未缓存输入 $1 · 调用 $2 次 · 缓存 $3%' },
  { pattern: /^([\d,.]+) loaded$/u, replace: '已加载 $1 条' },
  { pattern: /^Load ([\d,.]+) more$/u, replace: '再加载 $1 条' },
  { pattern: /^Inspect (.+) file evidence$/u, replace: '检查文件证据：$1' },
  { pattern: /^Inspect (.+) tool evidence$/u, replace: '检查工具证据：$1' },
  { pattern: /^Open evidence call for (.+)$/u, replace: '打开以下对象的证据调用：$1' },
  { pattern: /^Copy evidence call link for (.+)$/u, replace: '复制以下对象的证据调用链接：$1' },
  { pattern: /^Open largest call for (.+)$/u, replace: '打开以下对象的最大调用：$1' },
  { pattern: /^Copy largest call link for (.+)$/u, replace: '复制以下对象的最大调用链接：$1' },

  // Thread totals and lifecycle narration preserve thread names verbatim.
  { pattern: /^Showing ([\d,.]+) of ([\d,.]+) grouped threads$/u, replace: '显示 $1 / $2 个分组线程' },
  { pattern: /^([\d,.]+) selected calls$/u, replace: '已选择 $1 次调用' },
  { pattern: /^([\d,.]+) calls · ([\d,.]+(?:[KMBT])?) tokens · ([\d,.]+)% cache$/iu, replace: '$1 次调用 · $2 个token · 缓存 $3%' },
  { pattern: /^([\d,.]+) of ([\d,.]+) loaded$/u, replace: '已加载 $1 / $2 次' },
  { pattern: /^Show ([\d,.]+) more calls$/u, replace: '再显示 $1 次调用' },
  { pattern: /^Show first ([\d,.]+)$/u, replace: '显示前 $1 条' },
  { pattern: /^([\d,.]+) more available$/u, replace: '还有 $1 条可用' },
  { pattern: /^([\d,.]+) spawned$/u, replace: '已派生 $1 个' },
  { pattern: /^([\d,.]+) signals$/u, replace: '$1 个信号' },
  { pattern: /^Call ([\d,.]+)$/u, replace: '调用 $1' },
  { pattern: /^([\d,.]+) loaded threads$/u, replace: '已加载 $1 个线程' },
  { pattern: /^([\d,.]+) loaded threads combine at least 50,000 tokens with less than 35 percent cache reuse\.$/u, replace: '有 $1 个已加载线程的token数不低于 50,000，且缓存复用率低于 35%。' },
  { pattern: /^No loaded calls are available for (.+)\.$/u, replace: (_match, threadName) => `没有可用于${threadName === 'the selected thread' ? '所选线程' : `“${threadName}”`}的已加载调用。` },
  { pattern: /^([\d,.]+) calls are available for (.+); peak observed context use is ([\d,.]+) percent\.$/u, replace: '“$2”有 $1 次调用可用；观察到的上下文占用峰值为 $3%。' },
];

function scopeZhHans(scope: string): string {
  if (scope === '24 hours') return '过去 24 小时';
  if (scope === '7 days') return '过去 7 天';
  if (scope === 'recent rows') return '近期记录';
  return '全部时间范围';
}

function refreshPrefixZhHans(prefix: string): string {
  if (prefix === 'Cache hit; ') return '命中缓存；';
  if (prefix === 'Refreshed index; ') return '索引已刷新；';
  return '';
}

function presetZhHans(preset: string): string {
  if (preset === 'Highest Cost Threads') return '成本最高的线程';
  if (preset === 'Context Bloat') return '上下文膨胀';
  if (preset === 'Cache Misses') return '缓存未命中';
  if (preset === 'Pricing Gaps') return '定价缺口';
  if (preset === 'Codex Credits') return 'Codex 点数';
  return '推理峰值';
}

function datePresetZhHans(preset: string): string {
  if (preset === 'Today') return '今天';
  if (preset === 'This week') return '本周';
  if (preset === 'Last 7 days') return '过去 7 天';
  return '本月';
}

function effortSummaryZhHans(summary: string): string {
  const labels: Readonly<Record<string, string>> = {
    low: '低',
    medium: '中',
    high: '高',
    xhigh: '超高',
    ultra: '极高',
    max: '最大',
  };
  return summary
    .split(', ')
    .map(part => part.replace(/^(low|medium|high|xhigh|ultra|max) x([\d,]+)$/u, (_match, effort, count) => `${labels[String(effort)]} ×${count}`))
    .join('、');
}

function threadStatusZhHans(status: string): string {
  const labels: Readonly<Record<string, string>> = {
    'Official match': '官方精确匹配',
    Mixed: '混合匹配',
    Configured: '已配置',
    'Estimated mapping': '估算映射',
    'No mapped rate': '没有匹配的费率',
    'No price': '无定价',
  };
  return labels[status] ?? status;
}
