import type { ZhHansPattern } from './types';

export const diagnosticsReportsZhHansTranslations: Readonly<Record<string, string>> = {
  // Shared diagnostics and report labels.
  Action: '操作',
  Ascending: '升序',
  Blocked: '受阻',
  Cached: '已缓存',
  'Cached %': '缓存占比',
  Calls: '调用',
  Category: '类别',
  Copy: '复制',
  Credits: '点数',
  Descending: '降序',
  Effort: '推理强度',
  Evidence: '证据',
  Fallback: '回退数据',
  Finding: '发现',
  High: '高',
  Input: '输入',
  Largest: '最大调用',
  Latest: '最近时间',
  Loading: '正在加载',
  Low: '低',
  Medium: '中',
  Model: '模型',
  Occurrences: '出现次数',
  Open: '打开',
  Output: '输出',
  Planned: '计划中',
  Ready: '就绪',
  Reasoning: '推理',
  Reports: '报告',
  Stale: '已过期',
  Static: '静态',
  Thread: '线程',
  Threads: '线程',
  Time: '时间',
  Total: '总计',
  Uncached: '未缓存',
  Unknown: '未知',
  fallback: '回退数据',
  high: '高',
  low: '低',
  medium: '中',
  missing: '缺失',
  ready: '就绪',
  review: '需复核',
  snapshots: '快照',
  facts: '事实',
  Showing: '已显示',
  Show: '再显示',
  of: '/',
  more: '条',
  loaded: '条已加载',
  'loaded facts': '条已加载事实',
  matched: '条匹配',
  'evidence rows': '条证据记录',
  'calls -': '次调用 ·',
  'tokens -': 'token ·',
  'cache -': '缓存 ·',
  'Dashboard rows:': '仪表盘记录：',

  // Diagnostics notebook.
  'Diagnostics Notebook': '诊断工作台',
  'Technical report system behavior usage patterns.': '关于系统行为与用量模式的技术报告。',
  'Local Only': '仅限本地',
  'Loading diagnostic fact sources': '正在加载诊断事实来源',
  'Executive Findings': '核心发现',
  'Top observations aggregate telemetry': '基于聚合遥测数据的主要观察结果',
  'Notebook Index': '笔记本目录',
  'Jump to section': '跳转到章节',
  'Evidence Calls': '证据调用',
  'No matching calls': '没有匹配的调用',
  'No loaded aggregate call rows match diagnostic section.': '已加载的聚合调用中，没有记录与此诊断章节匹配。',
  'Static fallback facts': '静态回退事实',
  'Static aggregate fallback': '静态聚合回退数据',
  'Diagnostic fact type and name are required.': '必须提供诊断事实的类型和名称。',
  'Diagnostic facts require localhost dashboard server.': '诊断事实需要本机仪表盘服务器。',
  'Diagnostic facts require localhost dashboard API token.': '诊断事实需要本机仪表盘 API 令牌。',
  'Diagnostic snapshot refresh': '诊断快照刷新',
  'Diagnostic refresh status': '诊断刷新状态',
  'Structured Diagnostic Facts': '结构化诊断事实',
  'Top Diagnostic Facts': '主要诊断事实',
  'top diagnostic facts': '主要诊断事实',
  'Top Facts': '主要事实',
  'Tool and Function Activity': '工具与函数活动',
  'Compaction Activity': '上下文压缩活动',
  Compactions: '上下文压缩',
  compactions: '上下文压缩',
  Tools: '工具',
  tools: '工具',
  'Diagnostic fact modules': '诊断事实模块',
  'Sort facts': '事实排序',
  'Sort diagnostic facts': '诊断事实排序',
  'Sort diagnostic facts ascending': '按升序排列诊断事实',
  'Sort diagnostic facts descending': '按降序排列诊断事实',
  'Uncached input': '未缓存输入',
  'Total tokens': '总token数',
  'Cached input': '缓存输入',
  'Output tokens': '输出token数',
  'Largest call': '最大调用',
  'Associated calls': '关联调用',
  'Cache %': '缓存占比',
  'Latest time': '最近时间',
  'Fact name': '事实名称',
  'uncached input': '未缓存输入',
  'total tokens': '总token数',
  'cached input': '缓存输入',
  'output tokens': '输出token数',
  'largest call': '最大调用',
  'associated calls': '关联调用',
  'cache %': '缓存占比',
  'latest time': '最近时间',
  occurrences: '出现次数',
  'fact name': '事实名称',
  uncached: '未缓存',
  cache: '缓存',
  fact: '事实',
  unknown: '未知',
  uncategorized: '未分类',
  'No diagnostic facts matched the current aggregate data.': '当前聚合数据中没有匹配的诊断事实。',
  'Loading more facts...': '正在加载更多事实…',
  'Load more live facts': '加载更多实时事实',
  'Diagnostic Fact Calls': '诊断事实关联调用',
  'Diagnostic fact calls': '诊断事实关联调用',
  'No fact selected': '尚未选择事实',
  'No loaded rows': '没有已加载记录',
  'Sort calls': '调用排序',
  'Sort diagnostic fact calls': '诊断事实关联调用排序',
  'Sort diagnostic fact calls ascending': '按升序排列诊断事实关联调用',
  'Sort diagnostic fact calls descending': '按降序排列诊断事实关联调用',
  'Input tokens': '输入token数',
  'Reasoning tokens': '推理token数',
  'Loading fact calls...': '正在加载事实关联调用…',
  'Load more fact calls': '加载更多事实关联调用',
  'Loading rows...': '正在加载记录…',
  'Load more dashboard rows': '加载更多仪表盘记录',
  'Load all dashboard rows': '加载全部仪表盘记录',
  'No aggregate calls are associated with the selected diagnostic fact.': '没有聚合调用与所选诊断事实关联。',
  'Static aggregate fact calls': '静态聚合事实关联调用',
  'Waiting for live diagnostics': '正在等待实时诊断数据',
  'Loading calls for selected fact...': '正在加载所选事实的关联调用…',
  'Select a diagnostic fact': '请选择一项诊断事实',
  'Open associated aggregate calls in the full Call Investigator.': '在完整的调用分析器中打开关联的聚合调用。',

  // Diagnostic snapshot matrix.
  'Diagnostics Snapshot Matrix': '诊断快照矩阵',
  'Refreshing diagnostic snapshots': '正在刷新诊断快照',
  'Loading diagnostic snapshots': '正在加载诊断快照',
  'Refreshing diagnostic snapshots...': '正在刷新诊断快照…',
  'Loading diagnostic snapshots...': '正在加载诊断快照…',
  'Refresh snapshots': '刷新快照',
  Refreshing: '正在刷新',
  Reload: '重新加载',
  Reloading: '正在重新加载',
  'Static fallback snapshots': '静态回退快照',
  'Live diagnostic snapshots unavailable:': '实时诊断快照不可用：',
  'No aggregate rows in this snapshot.': '此快照中没有聚合记录。',
  'Show fewer': '收起',
  Overview: '概览',
  'Tool Output': '工具输出',
  'Git Interactions': 'Git 交互',
  'File Reads': '文件读取',
  'File Modifications': '文件修改',
  'Read Productivity': '读取成效',
  Concentration: '集中度',
  'What Is Driving Usage?': '是什么在推高用量？',
  'Usage Drain': '用量消耗',
  'Usage rows': '用量记录',
  'Cache ratio': '缓存比率',
  'Distinct aggregate thread labels': '聚合数据中的不同线程标签数',
  'Distinct model labels': '不同模型标签数',
  'Function calls': '函数调用',
  'Function outputs': '函数输出',
  'Original tokens': '原始token数',
  'Shell calls': 'Shell 调用',
  Roots: '根命令数',
  'Missing root': '缺失根命令',
  'No child commands': '没有子命令',
  'Git calls': 'Git 调用',
  'Git commands': 'Git 命令',
  'GitHub CLI': 'GitHub CLI',
  'Read events': '读取事件',
  Readers: '读取工具数',
  Events: '事件数',
  'Unique paths': '唯一路径数',
  'Largest event': '最大事件',
  'Modification events': '修改事件',
  'Modified later': '后续被修改',
  Rate: '比率',
  'Top thread share': '头部线程占比',
  Groups: '分组数',
  'largest impact': '影响最大',
  'Estimated cost': '预估成本',
  'Usage credits': '点数',
  'Computed unknown time': '计算时间未知',
  'Aggregate fallback module': '聚合回退模块',

  // Reports workspace and live report pack.
  'Report pack': '报告包',
  'Reports pack': '报告包',
  'Database error while building report pack': '构建报告包时发生数据库错误',
  'Live report pack requires the localhost dashboard server.': '实时报告包需要本机仪表盘服务器。',
  'Live report pack requires localhost dashboard API token.': '实时报告包需要本机仪表盘 API 令牌。',
  'Reports pack returned an unsupported schema.': '报告包返回了不受支持的数据结构。',
  'Live localhost report pack': '本机实时报告包',
  'Loaded dashboard aggregates': '已加载的仪表盘聚合数据',
  'Server timestamp unavailable': '服务器时间戳不可用',
  'Current dashboard snapshot': '当前仪表盘快照',
  'Refreshing selected report…': '正在刷新所选报告…',
  'Selected report refreshed': '所选报告已刷新',
  'Focused local research snapshots with their methods, limits, and investigator-linked evidence.': '聚焦本地数据的研究快照，附带分析方法、适用限制和可跳转至调用分析器的证据。',
  'Export selected': '导出所选报告',
  'Live report refresh requires the localhost server.': '实时刷新报告需要本机服务器。',
  'Refresh report': '刷新报告',
  'Live refresh unavailable': '实时刷新不可用',
  'Loading full-scope report pack': '正在加载完整范围的报告包',
  'Live report pack': '实时报告包',
  'No report available': '暂无可用报告',
  'No owner': '无负责人',
  'Select report': '选择报告',
  'Report evidence': '报告证据',
  'Report Evidence Calls': '报告证据调用',
  'Investigator linked': '已关联调用分析器',
  'Research Notes': '研究说明',
  'Interpretation boundary': '解读边界',
  Method: '方法',
  Caveat: '限制说明',
  'Evidence privacy': '证据隐私',
  'Raw context is not included here; inspect an explicitly linked call in Call Investigator.': '此处不包含原始上下文；如需查看，请在调用分析器中打开明确关联的调用。',
  'Generation Metadata': '生成元数据',
  'Provenance for this view': '此视图的数据来源',
  Source: '来源',
  Generated: '生成时间',
  Schema: '数据结构',
  Matched: '匹配记录',
  'dashboard aggregate model': '仪表盘聚合模型',
  'Static mode: using the loaded aggregate snapshot.': '静态模式：正在使用已加载的聚合快照。',
  'Loading live report pack…': '正在加载实时报告包…',
  'Refreshing live report pack…': '正在刷新实时报告包…',
  'Cached live report pack is stale; refresh is available.': '缓存的实时报告包已过期，可以刷新。',
  'Live report pack ready.': '实时报告包已就绪。',
  'No loaded aggregate calls match this selected report.': '已加载的聚合调用中，没有记录与所选报告匹配。',
  'Selected report evidence calls': '所选报告的证据调用',
  'loaded rows': '条已加载记录',
  'Est. Cost': '预估成本',
  'Speed proxy': '速度代理指标',
  'Filter fast-tagged and low-effort calls, then order by shortest duration and credit impact.': '筛选带有快速标签或低推理强度的调用，再按耗时从短到长及点数影响排序。',
  'Aggregate timing cannot distinguish model latency from tool, network, or queue time.': '聚合耗时无法区分模型延迟、工具耗时、网络耗时或排队时间。',
  'Fast/low-effort candidates · shortest duration first · top 8': '快速/低推理强度候选 · 耗时最短优先 · 前 8 项',
  'Cost concentration': '成本集中度',
  'Rank aggregate calls by estimated cost, breaking ties with total token volume.': '按预估成本对聚合调用排序，成本相同时以token总量决定顺序。',
  'Estimated local cost may differ from billing and excludes costs not represented in loaded rows.': '本地预估成本可能与实际账单不同，且不包含已加载记录未覆盖的费用。',
  'Highest estimated cost · token volume tie-break · top 8': '预估成本最高优先 · token量决定同分顺序 · 前 8 项',
  'Usage trajectory': '用量走势',
  'Rank aggregate calls by estimated Codex credit impact and compare the selected time series.': '按预估的 Codex 点数影响对聚合调用排序，并对比所选时间序列。',
  'Allowance and credit projections are local observations, not universal account limits.': '额度和点数预测仅基于本地观察，并非适用于所有账户的统一上限。',
  'Highest credit impact · token volume tie-break · top 8': '点数影响最高优先 · token量决定同分顺序 · 前 8 项',
  Percent: '百分比',
  'Under 5s': '5 秒以内',
  '5-15s': '5–15 秒',
  '15-30s': '15–30 秒',
  '30s+': '30 秒以上',
  'Selected report': '所选报告',
  'selected report': '所选报告',
  'Speed proxy evidence': '速度代理指标证据',
  'Cost concentration evidence': '成本集中度证据',
  'Usage trajectory evidence': '用量走势证据',
  'Raw context is available only through an explicitly linked Call Investigator record.': '只有通过明确关联的调用分析器记录才能查看原始上下文。',
  'Use left and right arrow keys to inspect chart values, or switch to the table for exact values.': '使用左右方向键查看图表数值，或切换到表格查看精确值。',
  'Observed period': '观察周期',
  'Weekly remaining': '每周剩余用量',
  'Observed drain': '观察到的消耗',
  'Predicted baseline': '预测基线',
  'Usage remaining': '剩余用量',
  'Allowance guide': '额度参考线',
  'Loaded-row baseline': '已加载记录基线',
  'Projected weekly credits': '预计每周点数',
  'Loaded-row credits': '已加载记录点数',
  'Cost Curves': '成本曲线',
  'Usage Drain Model': '用量消耗模型',
  'Fast Mode Proxy': '快速模式代理指标',
  'Weekly Credits': '每周点数',
  'Usage Remaining': '剩余用量',
  'Allowance Change': '额度变化',
  'Estimated cost concentration by loaded aggregate thread.': '按已加载聚合线程统计的预估成本集中度。',
  'Highest estimated credit-impact calls from loaded aggregate rows.': '已加载聚合记录中，预估点数影响最高的调用。',
  'Low-effort and fast-call candidates inferred from aggregate rows.': '根据聚合记录推断出的低推理强度和快速调用候选。',

  // Fallback findings and report copy used by the React aggregate model.
  'Cache Misses (Large Inputs)': '缓存未命中（大输入）',
  'High Model Effort': '高模型推理强度',
  'Tool Output Volume': '工具输出量',
  'Cache Behavior': '缓存行为',
  'Thread Efficiency': '线程效率',
  'Tool And Command Activity': '工具与命令活动',
  'Projected weekly credits declined from the baseline and partially recovered in the latest window.': '预计每周点数较基线下降，并在最近一个窗口中部分回升。',
  'Cache hit rate is healthy overall, with spikes aligned to large cache misses and cold resumes.': '总体缓存命中率良好，波动峰值与大规模缓存未命中及冷恢复相吻合。',
  'Long threads account for most estimated cost and are the clearest optimization target.': '长线程占据大部分预估成本，是最明确的优化目标。',
  'Command volume is stable with a slight upward trend; read and shell commands dominate.': '命令量总体稳定但略有上升，其中读取命令和 Shell 命令占主导。',
  'Plan-specific weekly credits, trend lines, and confidence intervals.': '按套餐展示每周点数、趋势线和置信区间。',
  'Observed remaining usage over time with reset handling.': '展示经过重置处理的剩余用量时间变化。',
  'Cumulative estimated cost by thread and concentration metrics.': '按线程统计累计预估成本及集中度指标。',
  'Actual-vs-predicted drain and feature group comparisons.': '实际与预测用量消耗及特征分组对比。',
  'Candidate detection, speedup histogram, and confidence breakdowns.': '候选检测、加速幅度直方图和置信度明细。',
  'Week-to-week allowance estimate changes with careful language.': '以审慎表述展示逐周额度估算变化。',

  // Settings.
  'Local configuration': '本地配置',
  Settings: '设置',
  'Inspect dashboard behavior and configuration truth without changing server-owned settings.': '查看仪表盘行为和实际配置状态，不会修改由服务器管理的设置。',
  'Live API available': '实时 API 可用',
  'Static snapshot': '静态快照',
  'Content access enabled': '内容访问已启用',
  'Content access gated': '内容访问受限',
  'Settings sections': '设置分类',
  Data: '数据',
  'Loaded history and local runtime state.': '已加载的历史记录和本地运行状态。',
  Estimates: '估算',
  'Pricing and allowance inputs used for local estimates.': '用于本地估算的定价与额度输入。',
  'Content Access': '内容访问',
  'Privacy boundaries and explicit raw-context gates.': '隐私边界与显式原始上下文访问门控。',
  Application: '应用',
  'Dashboard refresh, API, and language visibility.': '仪表盘刷新、API 与语言显示状态。',
  'Source Health': '数据源健康状态',
  'Configuration and parser diagnostics.': '配置与解析器诊断。',
  'Loaded Data': '已加载数据',
  'Served shell payload': '服务器提供的外壳载荷',
  'Embedded payload': '内嵌载荷',
  'Data window': '数据窗口',
  'Evidence rows': '证据记录',
  'Session scope': '会话范围',
  'Include archived': '包含已归档会话',
  'Usage index': '用量索引',
  'served shell': '服务器外壳数据',
  'embedded payload': '内嵌载荷',
  'Estimate Inputs': '估算输入',
  'Read-only local configuration': '只读本地配置',
  Pricing: '定价',
  Allowance: '额度',
  'Rate card': '费率表',
  Loaded: '已加载',
  'Not loaded': '未加载',
  'local pricing config': '本地定价配置',
  'local allowance config': '本地额度配置',
  'Allowance Windows': '额度窗口',
  'Allowance config': '额度配置',
  Usage: '用量',
  Window: '窗口',
  'No allowance windows configured': '尚未配置额度窗口',
  'Observed usage available': '可用观察用量数据',
  'Configured allowance window': '已配置的额度窗口',
  'Manual allowance windows and live observed usage': '手动额度窗口与实时观察用量',
  'Privacy Boundary': '隐私边界',
  'Payload mode': '载荷模式',
  'Project metadata': '项目元数据',
  'Raw context': '原始上下文',
  'Explicit localhost request, selected call only': '仅通过本机显式请求访问所选调用',
  'Disabled until context API is enabled': '启用上下文 API 前保持禁用',
  'Live requests': '实时请求',
  'Local API token present': '已提供本地 API 令牌',
  'Content Access Rules': '内容访问规则',
  'Local and explicit': '仅限本地且必须显式触发',
  'Aggregate payloads avoid prompts, assistant text, and raw tool output.': '聚合载荷不包含提示词、助手文本和原始工具输出。',
  'Raw context actions remain gated behind explicit Call Investigator controls.': '原始上下文操作仍须通过调用分析器中的显式控件触发。',
  'Live refresh and context requests stay local and require the dashboard API token.': '实时刷新和上下文请求仅在本机进行，并且需要仪表盘 API 令牌。',
  'Dashboard Runtime': '仪表盘运行状态',
  'Data connection': '数据连接',
  Enabled: '已启用',
  Paused: '已暂停',
  'Interface language': '界面语言',
  'English (en)': '英语（en）',
  'Configuration Checks': '配置检查',
  'Configuration and ingestion facts': '配置与数据导入状态',
  'Pricing snapshot': '定价快照',
  Configured: '已配置',
  'Not configured': '未配置',
  'Parser diagnostics': '解析器诊断',
  'No parser warnings': '没有解析器警告',
  'Usage deduplication': '用量去重',
  'Normal metadata': '普通元数据',
  'aggregate-only snapshot': '仅聚合数据快照',
  'Last 24 hours': '过去 24 小时',

  // Guided aggregate diagnostics.
  'Thread concentration': '线程集中度',
  'Review whether this thread still needs its full accumulated context.': '检查此线程是否仍需要保留全部累积上下文。',
  'Model mix': '模型构成',
  'Compare model choice against the actual work in the heaviest calls.': '对照最重调用的实际任务，检查模型选择是否合适。',
  'Low cache reuse': '缓存复用率低',
  'Look for repeated file reads, cold resumes, or broad context restatement.': '检查是否存在重复读取文件、冷恢复或大范围重述上下文。',
  'Reasoning-heavy output': '推理输出占比较高',
  'Check whether effort settings match task complexity.': '检查推理强度设置是否与任务复杂度匹配。',
  'Subagent activity': '子代理活动',
  'Separate direct work from delegated work when explaining usage growth.': '解释用量增长时，应区分直接执行与委派给子代理的工作。',
  'Context pressure': '上下文压力',
  'Inspect high-context threads before deciding whether to split work.': '决定是否拆分任务前，先检查上下文占用较高的线程。',
  'Command activity': '命令活动',
  'Use the Commands panel to see whether repetitive tooling is driving usage.': '使用“命令”面板检查重复工具操作是否在推高用量。',
  'Tool output volume': '工具输出量',
  'Trim noisy command output or use narrower file reads where possible.': '尽量精简冗长的命令输出，或缩小文件读取范围。',
  'Visible usage movement': '可见用量变化',
  'Use Usage Drain for allowance projection caveats and trend context.': '在“用量消耗”中查看额度预测的限制说明和趋势背景。',
  'Top thread by tokens': 'token量最高的线程',
  'Compare this thread against newer handoff threads before changing workflow.': '调整工作流前，将此线程与较新的交接线程进行比较。',
  'Top model bucket': 'token量最高的模型分组',
  'Check whether the model choice matches the work that dominates usage.': '检查模型选择是否与占用量最大的工作相匹配。',
  'Top effort bucket': 'token量最高的推理强度分组',
  'Compare effort mix with task complexity before changing defaults.': '更改默认值前，对照任务复杂度检查推理强度构成。',
  'Uncached input share': '未缓存输入占比',
  'High uncached share is a good place to look for repeated context loading.': '未缓存占比较高时，应优先排查重复加载上下文。',
  'Top review signal': '首要复核信号',
  'unknown thread': '未知线程',

  // Agentic findings, actions, caveats, and user-facing reasons.
  'Large calls produced little output': '大型调用的输出很少',
  'Large input/context usage with low output is a strong candidate for cold resumes, stale thread continuation, or low-value continuation.': '输入或上下文用量很大但输出很少，通常提示冷恢复、继续使用陈旧线程或低价值续接。',
  'Open the top calls, check whether a smaller fresh thread or preserved handoff would avoid resending large context.': '打开排名靠前的调用，检查改用较小的新线程或保留交接摘要能否避免重复发送大量上下文。',
  'Aggregate token/activity counts only; no raw fragments or command output.': '仅包含聚合token数和活动计数，不含原始片段或命令输出。',
  'The aggregate report cannot prove why output was low without a thread trace or explicit raw-context inspection.': '缺少线程轨迹或显式原始上下文检查时，聚合报告无法证明输出偏低的具体原因。',
  'Repeated shell command churn': 'Shell 命令反复空转',
  'Repeated shell roots, failures, or adjacent retries can waste turns and inflate tool-output/context pressure.': '反复使用相同 Shell 根命令、持续失败或相邻重试会浪费轮次，并加剧工具输出和上下文压力。',
  'Turn repeated probes into a small script, narrower command, or targeted test command.': '将重复探测整理成小型脚本、范围更窄的命令或有针对性的测试命令。',
  'Command roots and bounded labels only; raw command output is omitted.': '仅包含根命令和受限标签，省略原始命令输出。',
  'Strict aggregate evidence cannot always recover the exact shell intent or full command arguments.': '严格聚合证据不一定能还原确切的 Shell 意图或完整命令参数。',
  'Repeated file rediscovery': '重复查找同一文件',
  'Repeated safe file identities can indicate the agent keeps rediscovering the same context instead of using a durable summary or targeted helper.': '反复出现相同的安全文件标识，可能说明代理一直在重新查找同一上下文，而没有使用持久摘要或专用辅助工具。',
  'Summarize stable facts into project docs or build a small helper command for recurring lookups.': '将稳定信息整理到项目文档中，或为重复查询构建小型辅助命令。',
  'Safe path hashes, basenames, and aggregates only; full paths are omitted.': '仅包含安全的路径哈希、文件基本名和聚合数据，省略完整路径。',
  'The report can rank repeated safe file identities, but cannot tell whether each reread was necessary without task intent.': '报告可以对重复的安全文件标识排序，但缺少任务意图时无法判断每次重读是否必要。',
  'Ranked aggregate usage recommendations': '已排序的聚合用量建议',
  'Existing recommendation scoring combines aggregate cost, cache, context, and pricing signals.': '现有建议评分综合了聚合成本、缓存、上下文和定价信号。',
  'Start with the highest recommendation score, then verify with the specific diagnostic tool.': '从评分最高的建议开始，再使用相应诊断工具进行验证。',
  'Aggregate recommendations only; no prompt or tool-output text.': '仅包含聚合建议，不含提示词或工具输出文本。',
  'Recommendation scores do not know whether an expensive call produced high-value work.': '建议评分无法判断高成本调用是否产出了高价值结果。',
  'Local Codex logs only; this is not an official OpenAI usage ledger.': '仅基于本地 Codex 日志，并非 OpenAI 官方用量账本。',
  'Archived sessions are excluded unless include_archived is true.': '除非 include_archived 为 true，否则不包含已归档会话。',
  'Run weekly evidence-graded allowance diagnostics before interpreting 5-hour noise.': '解读 5 小时窗口的噪声前，先运行带证据等级的每周额度诊断。',
  'Create strict local evidence bundle when the user wants to share allowance-change evidence.': '用户需要分享额度变化证据时，创建严格隐私模式的本地证据包。',
  'Weekly allowance evidence is the primary signal; 5-hour counters are rolling-window context.': '每周额度证据是主要信号；5 小时计数器仅提供滚动窗口背景。',
  'Confirm index freshness and row counts.': '确认索引新鲜度和记录数。',
  "Rank projects, threads, models, or dates depending on the user's next question.": '根据用户接下来的问题，对项目、线程、模型或日期进行排序。',
  'Open dashboard-shaped evidence cards for top aggregate drivers.': '打开与仪表盘一致的证据卡片，查看主要聚合驱动因素。',
  'No strong local signal at default thresholds': '默认阈值下没有明显的本地信号',
  'The current aggregate diagnostics did not find a clear candidate at the default threshold.': '当前聚合诊断在默认阈值下没有发现明确候选。',
  'Lower thresholds, widen the time window, include archived sessions, or inspect top aggregate calls.': '降低阈值、扩大时间窗口、纳入已归档会话，或检查排名靠前的聚合调用。',
  'No raw context needed for this follow-up.': '此后续检查无需原始上下文。',
  'No supported aggregate signal was found at the selected thresholds.': '所选阈值下未发现受支持的聚合信号。',
};

export const diagnosticsReportsZhHansPatterns: ReadonlyArray<ZhHansPattern> = [
  // Diagnostics counts, sort descriptions, states, and controls.
  {
    pattern: /^Live (.+): ([\d,.]+)$/u,
    replace: (_match, noun, count) => `实时${translateEmbeddedUiText(noun)}：${count}`,
  },
  {
    pattern: /^Live (.+) unavailable: (.+)$/u,
    replace: (_match, noun, error) => `实时${translateEmbeddedUiText(noun)}不可用：${error}`,
  },
  {
    pattern: /^(.+) module - ([\d,.]+) loaded \/ ([\d,.]+) matched - (.+)$/u,
    replace: (_match, title, loaded, matched, sort) =>
      `${translateEmbeddedUiText(title)}模块 · 已加载 ${loaded} / 匹配 ${matched} · ${translateSortDescription(sort)}`,
  },
  {
    pattern: /^(.+) module - ([\d,.]+) matched - (.+)$/u,
    replace: (_match, title, matched, sort) =>
      `${translateEmbeddedUiText(title)}模块 · 匹配 ${matched} 条 · ${translateSortDescription(sort)}`,
  },
  {
    pattern: /^sorted by (.+) (descending|ascending)$/u,
    replace: (_match, label, direction) =>
      `按${translateEmbeddedUiText(label)}${direction === 'descending' ? '降序' : '升序'}排列`,
  },
  { pattern: /^([\d,.]+) loaded \/ ([\d,.]+) matched$/u, replace: '已加载 $1 / 匹配 $2' },
  { pattern: /^([\d,.]+) matched$/u, replace: '匹配 $1 条' },
  { pattern: /^\/ ([\d,.]+) matched$/u, replace: '· 共匹配 $1 条' },
  {
    pattern: /^(High|Medium|Low) confidence$/u,
    replace: (_match, confidence) => `${translateEmbeddedUiText(confidence)}置信度`,
  },
  { pattern: /^([\d,.]+) calls - ([\d.]+%) cache$/u, replace: '$1 次调用 · 缓存占比 $2' },
  { pattern: /^([\d,.]+) of ([\d,.]+) live fact calls$/u, replace: '已加载 $1 / $2 次实时事实关联调用' },
  { pattern: /^([\d,.]+) fallback aggregate calls$/u, replace: '$1 次回退聚合调用' },
  {
    pattern: /^Showing ([\d,.]+) of ([\d,.]+) calls - (.+)$/u,
    replace: (_match, shown, total, sort) => `已显示 ${shown} / ${total} 次调用 · ${translateSortDescription(sort)}`,
  },
  { pattern: /^Showing ([\d,.]+) of ([\d,.]+) calls$/u, replace: '已显示 $1 / $2 次调用' },
  { pattern: /^Showing ([\d,.]+) of ([\d,.]+) loaded facts$/u, replace: '已显示 $1 / $2 条已加载事实' },
  { pattern: /^Showing ([\d,.]+) of ([\d,.]+) loaded facts \/ ([\d,.]+) matched$/u, replace: '已显示 $1 / $2 条已加载事实 · 共匹配 $3 条' },
  { pattern: /^Show ([\d,.]+) more$/u, replace: '再显示 $1 条' },
  { pattern: /^Dashboard rows: ([\d,.]+) of ([\d,.]+) loaded$/u, replace: '仪表盘记录：已加载 $1 / $2 条' },
  { pattern: /^([\d,.]+) aggregate rows$/u, replace: '$1 条聚合记录' },
  { pattern: /^([\d,.]+(?:[KMBT])?) tokens$/iu, replace: '$1 个token' },
  { pattern: /^([\d,.]+(?:[KMBT])?) uncached$/iu, replace: '$1 个未缓存token' },
  { pattern: /^([\d,.]+) calls$/u, replace: '$1 次调用' },
  { pattern: /^([\d,.]+) reads$/u, replace: '$1 次读取' },
  { pattern: /^([\d,.]+) modified later$/u, replace: '$1 次后续被修改' },
  { pattern: /^([\d,.]+) child commands$/u, replace: '$1 个子命令' },
  { pattern: /^Show ([\d,.]+) child command$/u, replace: '显示 $1 个子命令' },
  { pattern: /^Show ([\d,.]+) child commands$/u, replace: '显示 $1 个子命令' },
  { pattern: /^Showing all ([\d,.]+) rows$/u, replace: '正在显示全部 $1 条记录' },
  { pattern: /^Showing ([\d,.]+) of ([\d,.]+) rows$/u, replace: '正在显示 $1 / $2 条记录' },
  { pattern: /^Live snapshots: ([\d,.]+)$/u, replace: '实时快照：$1 个' },
  { pattern: /^Snapshot refresh failed: (.+)$/u, replace: '快照刷新失败：$1' },
  { pattern: /^Live diagnostic snapshots unavailable: (.+)$/u, replace: '实时诊断快照不可用：$1' },
  {
    pattern: /^(.+) request failed with HTTP ([\d]+)$/u,
    replace: (_match, title, status) => `${translateEmbeddedUiText(title)}请求失败（HTTP ${status}）`,
  },
  {
    pattern: /^(.+) failed with HTTP ([\d]+)$/u,
    replace: (_match, title, status) => `${translateEmbeddedUiText(title)}失败（HTTP ${status}）`,
  },
  { pattern: /^Diagnostic refresh failed: (.+)$/u, replace: '诊断刷新失败：$1' },
  { pattern: /^Unknown diagnostic snapshot: (.+)$/u, replace: '未知诊断快照：$1' },
  { pattern: /^(.+) unavailable: (.+)$/u, replace: (_match, title, error) => `${translateEmbeddedUiText(title)}不可用：${error}` },
  {
    pattern: /^Reload (.+) diagnostic snapshot$/u,
    replace: (_match, title) => `重新加载${translateEmbeddedUiText(title)}诊断快照`,
  },
  {
    pattern: /^Open investigator for diagnostic snapshot (.+?) (.+)$/u,
    replace: (_match, title, label) => `在调用分析器中打开${translateEmbeddedUiText(title)}诊断快照：${label}`,
  },
  {
    pattern: /^Copy link for diagnostic snapshot (.+?) (.+)$/u,
    replace: (_match, title, label) => `复制${translateEmbeddedUiText(title)}诊断快照链接：${label}`,
  },
  { pattern: /^Open investigator for diagnostic call (.+)$/u, replace: '在调用分析器中打开诊断调用：$1' },
  { pattern: /^Copy link for diagnostic call (.+)$/u, replace: '复制诊断调用链接：$1' },
  { pattern: /^Open investigator diagnostic fact call (.+)$/u, replace: '在调用分析器中打开诊断事实关联调用：$1' },
  { pattern: /^Copy link for diagnostic fact call (.+)$/u, replace: '复制诊断事实关联调用链接：$1' },
  { pattern: /^Open investigator largest diagnostic fact call (.+)$/u, replace: '在调用分析器中打开最大诊断事实关联调用：$1' },
  { pattern: /^Copy link for largest diagnostic fact call (.+)$/u, replace: '复制最大诊断事实关联调用链接：$1' },
  { pattern: /^Open call row in investigator for report side evidence call (.+)$/u, replace: '在调用分析器中打开报告证据调用：$1' },
  { pattern: /^Copy link for report side evidence call (.+)$/u, replace: '复制报告证据调用链接：$1' },
  {
    pattern: /^Computed unknown time · history (.+?) · logs scanned (.+?) · rows scanned (.+)$/u,
    replace: (_match, scope, logs, rows) =>
      `计算时间未知 · 历史范围：${translateHistoryScope(scope)} · 已扫描 ${logs} 个日志 · ${rows} 条记录`,
  },
  {
    pattern: /^Computed unknown time · history (.+?) · logs scanned (.+)$/u,
    replace: (_match, scope, logs) =>
      `计算时间未知 · 历史范围：${translateHistoryScope(scope)} · 已扫描 ${logs} 个日志`,
  },
  {
    pattern: /^Computed (.+?) · history (.+?) · logs scanned (.+?) · rows scanned (.+)$/u,
    replace: (_match, computed, scope, logs, rows) =>
      `计算于 ${translateShortTimestamp(computed)} · 历史范围：${translateHistoryScope(scope)} · 已扫描 ${logs} 个日志 · ${rows} 条记录`,
  },
  {
    pattern: /^Computed (.+?) · history (.+?) · logs scanned (.+)$/u,
    replace: (_match, computed, scope, logs) =>
      `计算于 ${translateShortTimestamp(computed)} · 历史范围：${translateHistoryScope(scope)} · 已扫描 ${logs} 个日志`,
  },
  { pattern: /^Computed (.+)$/u, replace: (_match, computed) => `计算于 ${translateShortTimestamp(computed)}` },
  {
    pattern: /^history (.+) · logs scanned ([\d,.]+) · rows scanned ([\d,.]+)$/u,
    replace: (_match, scope, logs, rows) =>
      `历史范围：${translateHistoryScope(scope)} · 已扫描 ${logs} 个日志 · ${rows} 条记录`,
  },
  {
    pattern: /^history (.+) · logs scanned ([\d,.]+)$/u,
    replace: (_match, scope, logs) => `历史范围：${translateHistoryScope(scope)} · 已扫描 ${logs} 个日志`,
  },
  {
    pattern: /^history (.+) · no stored snapshot$/u,
    replace: (_match, scope) => `历史范围：${translateHistoryScope(scope)} · 没有已存储快照`,
  },
  {
    pattern: /^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) ([\d]{1,2}), ([\d]{1,2}):([\d]{2}) (AM|PM)$/u,
    replace: match => translateShortTimestamp(match),
  },

  // Reports, evidence, and visualization copy.
  { pattern: /^Refresh failed: (.+)\. Showing cached live report pack\.$/u, replace: '刷新失败：$1。正在显示缓存的实时报告包。' },
  { pattern: /^Report pack unavailable: (.+)$/u, replace: '报告包不可用：$1' },
  { pattern: /^Live report pack unavailable: (.+)\. Using loaded aggregate fallback\.$/u, replace: '实时报告包不可用：$1。正在使用已加载的聚合回退数据。' },
  { pattern: /^Exported (.+)$/u, replace: (_match, title) => `已导出${translateEmbeddedUiText(title)}` },
  { pattern: /^(.+) selected$/u, replace: (_match, title) => `已选择${translateEmbeddedUiText(title)}` },
  {
    pattern: /^(Live localhost report pack|Loaded dashboard aggregates) · (.+)$/u,
    replace: (_match, source, selection) =>
      `${translateEmbeddedUiText(source)} · ${translateEmbeddedUiText(selection)}`,
  },
  { pattern: /^([\d,.]+) evidence rows$/u, replace: '$1 条证据记录' },
  { pattern: /^([\d,.]+) aggregate rows · select a row to open Call Investigator$/u, replace: '$1 条聚合记录 · 选择记录可在调用分析器中打开' },
  { pattern: /^([\d,.]+) loaded rows$/u, replace: '$1 条已加载记录' },
  {
    pattern: /^([\d,.]+) loaded calls are fast-tagged or low effort\. Duration is a proxy, not a quality score\.$/u,
    replace: '$1 次已加载调用带有快速标签或采用低推理强度。耗时只是代理指标，并非质量评分。',
  },
  {
    pattern: /^([\d,.]+) highest-cost loaded calls anchor this report\. Estimates use the local pricing model\.$/u,
    replace: '此报告以成本最高的 $1 次已加载调用为核心，估算采用本地定价模型。',
  },
  {
    pattern: /^([\d,.]+) highest credit-impact loaded calls support the selected usage report\.$/u,
    replace: '点数影响最高的 $1 次已加载调用为所选用量报告提供证据。',
  },
  {
    pattern: /^No loaded aggregate data is available for (.+)\.$/u,
    replace: (_match, title) => `${translateEmbeddedUiText(title)}暂无已加载的聚合数据。`,
  },
  {
    pattern: /^(.+) contains ([\d,.]+) plotted rows\. (.+)$/u,
    replace: (_match, title, rows, finding) => `${translateEmbeddedUiText(title)}包含 ${rows} 条绘图记录。${translateEmbeddedUiText(finding)}`,
  },
  {
    pattern: /^No plotted rows are available for (.+)\.$/u,
    replace: (_match, title) => `${translateEmbeddedUiText(title)}没有可绘制的记录。`,
  },
  {
    pattern: /^(.+) report data$/u,
    replace: (_match, title) => `${translateEmbeddedUiText(title)}报告数据`,
  },
  { pattern: /^([A-Za-z][A-Za-z0-9 ._-]*) observed$/u, replace: '$1 观测值' },
  { pattern: /^([A-Za-z][A-Za-z0-9 ._-]*) trend$/u, replace: '$1 趋势' },
  { pattern: /^Point ([\d,.]+)$/u, replace: '数据点 $1' },
  { pattern: /^(.+) low$/u, replace: (_match, label) => `${translateEmbeddedUiText(label)}下限` },
  { pattern: /^(.+) high$/u, replace: (_match, label) => `${translateEmbeddedUiText(label)}上限` },
  { pattern: /^Long Thread: (.+)$/u, replace: '长线程：$1' },
  { pattern: /^([\d,.]+) loaded calls and ([\d,.]+) tokens in this thread\.$/u, replace: '此线程包含 $1 次已加载调用和 $2 个token。' },
  { pattern: /^([\d,.]+) loaded calls show low cache reuse or large uncached input\.$/u, replace: '$1 次已加载调用存在缓存复用率低或未缓存输入量大的情况。' },
  { pattern: /^([\d,.]+) loaded calls use high effort or report reasoning output\.$/u, replace: '$1 次已加载调用采用高推理强度或记录了推理输出。' },
  { pattern: /^([\d,.]+) loaded calls have high output volume or file-heavy\/subagent tags\.$/u, replace: '$1 次已加载调用的输出量较高，或带有文件密集/子代理标签。' },

  // Settings values and diagnostics.
  { pattern: /^Most recent ([\d,.]+)$/u, replace: '最近 $1 条记录' },
  { pattern: /^([\d,.]+) of ([\d,.]+)$/u, replace: '$1 / $2' },
  {
    pattern: /^Observed (.+)$/u,
    replace: (_match, label) => `观察值：${translateEmbeddedUiText(label)}`,
  },
  {
    pattern: /^Configured (.+)$/u,
    replace: (_match, label) => `已配置：${translateEmbeddedUiText(label)}`,
  },
  { pattern: /^([\d.]+%) remaining$/u, replace: '剩余 $1' },
  { pattern: /^([\d.]+%) used$/u, replace: '已用 $1' },
  { pattern: /^([\d,.]+) cr left$/u, replace: '剩余 $1 点' },
  { pattern: /^([\d,.]+) cr total$/u, replace: '总计 $1 点' },
  { pattern: /^resets (.+)$/u, replace: '重置于 $1' },
  {
    pattern: /^(?:[\d.]+% (?:remaining|used)|[\d,.]+ cr (?:left|total)|resets .+)(?: · (?:[\d.]+% (?:remaining|used)|[\d,.]+ cr (?:left|total)|resets .+))*$/u,
    replace: match => translateAllowanceWindowValue(match),
  },
  {
    pattern: /^.+(?: · (?:plan|limit|observed) .+)+$/u,
    replace: match => translateAllowanceMetadata(match),
  },
  { pattern: /^Config error: (.+)$/u, replace: '配置错误：$1' },
  { pattern: /^Rate-card error: (.+)$/u, replace: '费率表错误：$1' },
  { pattern: /^([\d,.]+) copied rows excluded; ([\d,.]+) physical rows preserved$/u, replace: '已排除 $1 条复制记录；保留 $2 条物理记录' },
  { pattern: /^([\d,.]+) parser diagnostics: (.+)$/u, replace: '$1 项解析器诊断：$2' },
  {
    pattern: /^([^:]+): (cwd redacted|project names redacted|git remote hidden|relative cwd hidden|git branch hidden|tags hidden|aliases preserved)(?:, .+)*$/u,
    replace: match => translatePrivacyMetadata(match),
  },

  // Guided-signal findings retain thread/model labels and numerical evidence.
  { pattern: /^(.+) accounts for ([\d.]+%) of tokens\.$/u, replace: '$1 占token总量的 $2。' },
  { pattern: /^(.+) is the largest model bucket by tokens\.$/u, replace: '$1 是token量最大的模型分组。' },
  { pattern: /^Overall cache ratio is ([\d.]+%)\.$/u, replace: '总体缓存比率为 $1。' },
  { pattern: /^Reasoning output is ([\d.]+%) of total tokens\.$/u, replace: '推理输出占token总量的 $1。' },
  { pattern: /^Subagent-linked rows are ([\d.]+%) of calls\.$/u, replace: '子代理关联记录占全部调用的 $1。' },
  { pattern: /^([\d.]+%) of calls used at least 60% of context\.$/u, replace: '$1 的调用使用了至少 60% 的上下文窗口。' },
  { pattern: /^([\d,.]+) shell calls across ([\d,.]+) command roots\.$/u, replace: '$1 次 Shell 调用，涉及 $2 个根命令。' },
  { pattern: /^Terminal\/tool outputs account for ([\d,.]+) parsed output tokens\.$/u, replace: '终端/工具输出共占 $1 个已解析输出token。' },
  { pattern: /^([\d,.]+) positive visible-usage spans are available\.$/u, replace: '现有 $1 个可见用量正向变化区间。' },
];

function translateEmbeddedUiText(value: string): string {
  const exact = diagnosticsReportsZhHansTranslations[value];
  if (exact) return exact;
  let match = value.match(/^([\d,.]+) loaded calls are fast-tagged or low effort\. Duration is a proxy, not a quality score\.$/u);
  if (match) return `${match[1]} 次已加载调用带有快速标签或采用低推理强度。耗时只是代理指标，并非质量评分。`;
  match = value.match(/^([\d,.]+) highest-cost loaded calls anchor this report\. Estimates use the local pricing model\.$/u);
  if (match) return `此报告以成本最高的 ${match[1]} 次已加载调用为核心，估算采用本地定价模型。`;
  match = value.match(/^([\d,.]+) highest credit-impact loaded calls support the selected usage report\.$/u);
  if (match) return `点数影响最高的 ${match[1]} 次已加载调用为所选用量报告提供证据。`;
  match = value.match(/^([A-Za-z][A-Za-z0-9 ._-]*) observed$/u);
  if (match) return `${match[1]} 观测值`;
  match = value.match(/^([A-Za-z][A-Za-z0-9 ._-]*) trend$/u);
  if (match) return `${match[1]} 趋势`;
  return value;
}

function translateSortDescription(value: string): string {
  const match = value.match(/^sorted by (.+) (descending|ascending)$/u);
  if (!match) return translateEmbeddedUiText(value);
  return `按${translateEmbeddedUiText(match[1])}${match[2] === 'descending' ? '降序' : '升序'}排列`;
}

function translateHistoryScope(value: string): string {
  if (value === 'active') return '活动会话';
  if (value === 'all') return '全部历史记录';
  return value;
}

function translateShortTimestamp(value: string): string {
  const match = value.match(/^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) ([\d]{1,2}), ([\d]{1,2}):([\d]{2}) (AM|PM)$/u);
  if (!match) return value;
  const months: Readonly<Record<string, number>> = {
    Jan: 1,
    Feb: 2,
    Mar: 3,
    Apr: 4,
    May: 5,
    Jun: 6,
    Jul: 7,
    Aug: 8,
    Sep: 9,
    Oct: 10,
    Nov: 11,
    Dec: 12,
  };
  const hour12 = Number(match[3]);
  const hour24 = match[5] === 'PM' ? (hour12 % 12) + 12 : hour12 % 12;
  return `${months[match[1]]}月${Number(match[2])}日 ${String(hour24).padStart(2, '0')}:${match[4]}`;
}

function translateAllowanceMetadata(value: string): string {
  return value
    .split(' · ')
    .map(part => {
      if (part.startsWith('plan ')) return `套餐 ${part.slice(5)}`;
      if (part.startsWith('limit ')) return `限制 ${part.slice(6)}`;
      if (part.startsWith('observed ')) return `观察于 ${part.slice(9)}`;
      return part;
    })
    .join(' · ');
}

function translateAllowanceWindowValue(value: string): string {
  return value
    .split(' · ')
    .map(part => {
      const percent = part.match(/^([\d.]+%) (remaining|used)$/u);
      if (percent) return percent[2] === 'remaining' ? `剩余 ${percent[1]}` : `已用 ${percent[1]}`;
      const credits = part.match(/^([\d,.]+) cr (left|total)$/u);
      if (credits) return credits[2] === 'left' ? `剩余 ${credits[1]} 点` : `总计 ${credits[1]} 点`;
      if (part.startsWith('resets ')) return `重置于 ${part.slice(7)}`;
      return part;
    })
    .join(' · ');
}

function translatePrivacyMetadata(value: string): string {
  const separator = value.indexOf(': ');
  if (separator < 0) return value;
  const mode = value.slice(0, separator);
  const flagTranslations: Readonly<Record<string, string>> = {
    'cwd redacted': '工作目录已脱敏',
    'project names redacted': '项目名称已脱敏',
    'git remote hidden': 'Git 远程信息已隐藏',
    'relative cwd hidden': '相对工作目录已隐藏',
    'git branch hidden': 'Git 分支已隐藏',
    'tags hidden': '标签已隐藏',
    'aliases preserved': '已保留别名',
  };
  const flags = value
    .slice(separator + 2)
    .split(', ')
    .map(flag => flagTranslations[flag] ?? flag)
    .join('、');
  return `${mode}：${flags}`;
}
